local data = {	{
		id = "LegendaryBeastTiger", 
		min_level = 0, 
		monster = "Farric Tiger Alpha", 
	},
	{
		id = "LegendaryBeastHellionFire", 
		min_level = 0, 
		monster = "Farric Flame Hellion Alpha", 
	},
	{
		id = "LegendaryBeastHellionIce", 
		min_level = 0, 
		monster = "Farric Frost Hellion Alpha", 
	},
	{
		id = "LegendaryBeastLynx", 
		min_level = 0, 
		monster = "Farric Lynx Alpha", 
	},
	{
		id = "LegendaryBeastChieftain", 
		min_level = 0, 
		monster = "Farric Chieftain", 
	},
	{
		id = "LegendaryBeastMonkey", 
		min_level = 0, 
		monster = "Farric Ape", 
	},
	{
		id = "LegendaryBeastGoatman", 
		min_level = 0, 
		monster = "Farric Goatman", 
	},
	{
		id = "LegendaryBeastWolf", 
		min_level = 0, 
		monster = "Farric Wolf Alpha", 
	},
	{
		id = "LegendaryBeastHound", 
		min_level = 0, 
		monster = "Farric Magma Hound", 
	},
	{
		id = "LegendaryBeastPitbull", 
		min_level = 0, 
		monster = "Farric Pit Hound", 
	},
	{
		id = "LegendaryBeastBeast", 
		min_level = 0, 
		monster = "Farric Gargantuan", 
	},
	{
		id = "LegendaryBeastUrsa", 
		min_level = 0, 
		monster = "Farric Ursa", 
	},
	{
		id = "LegendaryBeastBull", 
		min_level = 0, 
		monster = "Farric Taurus", 
	},
	{
		id = "LegendaryBeastSpiker", 
		min_level = 0, 
		monster = "Farric Goliath", 
	},
	{
		id = "LegendaryBeastKiweth", 
		min_level = 0, 
		monster = "Saqawine Retch", 
	},
	{
		id = "LegendaryBeastVulture", 
		min_level = 0, 
		monster = "Saqawine Vulture", 
	},
	{
		id = "LegendaryBeastRhoa", 
		min_level = 0, 
		monster = "Saqawine Rhoa", 
	},
	{
		id = "LegendaryBeastRhex", 
		min_level = 0, 
		monster = "Saqawine Rhex", 
	},
	{
		id = "LegendaryBeastForestSnake", 
		min_level = 0, 
		monster = "Saqawine Cobra", 
	},
	{
		id = "LegendaryBeastSandSnake", 
		min_level = 0, 
		monster = "Saqawine Blood Viper", 
	},
	{
		id = "LegendaryBeastIguana", 
		min_level = 0, 
		monster = "Saqawine Chimeral", 
	},
	{
		id = "LegendaryBeastCarrionQueen", 
		min_level = 0, 
		monster = "Fenumal Queen", 
	},
	{
		id = "LegendaryBeastSandLeaper", 
		min_level = 0, 
		monster = "Fenumal Scrabbler", 
	},
	{
		id = "LegendaryBeastDevourer", 
		min_level = 0, 
		monster = "Fenumal Devourer", 
	},
	{
		id = "LegendaryBeastPlagueSpider", 
		min_level = 0, 
		monster = "Fenumal Plagued Arachnid", 
	},
	{
		id = "LegendaryBeastPlatedSpider", 
		min_level = 0, 
		monster = "Fenumal Hybrid Arachnid", 
	},
	{
		id = "LegendaryBeastSpider", 
		min_level = 0, 
		monster = "Fenumal Widow", 
	},
	{
		id = "LegendaryBeastScorpion", 
		min_level = 0, 
		monster = "Fenumal Scorpion", 
	},
	{
		id = "LegendaryBeastParasiticSquid", 
		min_level = 0, 
		monster = "Craicic Vassal", 
	},
	{
		id = "LegendaryBeastSirenSpawn", 
		min_level = 0, 
		monster = "Craicic Squid", 
	},
	{
		id = "LegendaryBeastSquid", 
		min_level = 0, 
		monster = "Craicic Watcher", 
	},
	{
		id = "LegendaryBeastSandSpitter", 
		min_level = 0, 
		monster = "Craicic Sand Spitter", 
	},
	{
		id = "LegendaryBeastShieldCrab", 
		min_level = 0, 
		monster = "Craicic Shield Crab", 
	},
	{
		id = "LegendaryBeastCrab", 
		min_level = 0, 
		monster = "Craicic Savage Crab", 
	},
	{
		id = "LegendaryBeastCrab2", 
		min_level = 0, 
		monster = "Craicic Spider Crab", 
	},
	{
		id = "LegendaryBeastFrog", 
		min_level = 0, 
		monster = "Craicic Maw", 
	},
	{
		id = "LegendaryBeastGemFrog", 
		min_level = 0, 
		monster = "Craicic Chimeral", 
	},
	{
		id = "RareFeline", 
		min_level = 0, 
		beast_group = "Felines", 
		rarity = "Rare", 
	},
	{
		id = "RarePrimate", 
		min_level = 0, 
		beast_group = "Primates", 
		rarity = "Rare", 
	},
	{
		id = "RareCanine", 
		min_level = 0, 
		beast_group = "Canines", 
		rarity = "Rare", 
	},
	{
		id = "RareUrsa", 
		min_level = 0, 
		beast_group = "Ursae", 
		rarity = "Rare", 
	},
	{
		id = "RareUnnatural", 
		min_level = 0, 
		beast_group = "Unnaturals", 
		rarity = "Rare", 
	},
	{
		id = "RareAvian", 
		min_level = 0, 
		beast_group = "Avians", 
		rarity = "Rare", 
	},
	{
		id = "RareReptile", 
		min_level = 0, 
		beast_group = "Reptiles", 
		rarity = "Rare", 
	},
	{
		id = "RareInsect", 
		min_level = 0, 
		beast_group = "Insects", 
		rarity = "Rare", 
	},
	{
		id = "RareArachnid", 
		min_level = 0, 
		beast_group = "Arachnids", 
		rarity = "Rare", 
	},
	{
		id = "RareCephalopod", 
		min_level = 0, 
		beast_group = "Cephalopods", 
		rarity = "Rare", 
	},
	{
		id = "RareCrustacean", 
		min_level = 0, 
		beast_group = "Crustaceans", 
		rarity = "Rare", 
	},
	{
		id = "RareAmphibian", 
		min_level = 0, 
		beast_group = "Amphibians", 
		rarity = "Rare", 
	},
	{
		id = "RareWilds", 
		min_level = 0, 
		family = "The Wilds", 
		rarity = "Rare", 
	},
	{
		id = "RareSands", 
		min_level = 0, 
		family = "The Sands", 
		rarity = "Rare", 
	},
	{
		id = "RareCaverns", 
		min_level = 0, 
		family = "The Caverns", 
		rarity = "Rare", 
	},
	{
		id = "RareDepths", 
		min_level = 0, 
		family = "The Deep", 
		rarity = "Rare", 
	},
	{
		id = "RareWildsLevel70Plus", 
		min_level = 70, 
		family = "The Wilds", 
		rarity = "Rare", 
	},
	{
		id = "RareSandsLevel70Plus", 
		min_level = 70, 
		family = "The Sands", 
		rarity = "Rare", 
	},
	{
		id = "RareCavernsLevel70Plus", 
		min_level = 70, 
		family = "The Caverns", 
		rarity = "Rare", 
	},
	{
		id = "RareDepthsLevel70Plus", 
		min_level = 70, 
		family = "The Deep", 
		rarity = "Rare", 
	},
	{
		id = "UniqueOozebackBloom", 
		min_level = 0, 
		monster = "Oozeback Bloom", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheDeepDweller", 
		min_level = 0, 
		monster = "The Dweller of the Deep", 
		rarity = "Unique", 
	},
	{
		id = "UniqueUngulath", 
		min_level = 0, 
		monster = "Ungulath", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheBurningMenace", 
		min_level = 0, 
		monster = "The Burning Menace", 
		rarity = "Unique", 
	},
	{
		id = "UniqueBroodPrincess", 
		min_level = 0, 
		monster = "Brood Princess", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheFaun", 
		min_level = 0, 
		monster = "The Faun", 
		rarity = "Unique", 
	},
	{
		id = "UniqueAmarissaDaughterOfMerveil", 
		min_level = 0, 
		monster = "Amarissa, Daughter of Merveil", 
		rarity = "Unique", 
	},
	{
		id = "UniqueAmbrosiaDaughterOfMerveil", 
		min_level = 0, 
		monster = "Ambrosia, Daughter of Merveil", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheGreatWhiteBeast", 
		min_level = 0, 
		monster = "The Great White Beast", 
		rarity = "Unique", 
	},
	{
		id = "UniqueBlackDeath", 
		min_level = 0, 
		monster = "Black Death", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheWeaver", 
		min_level = 0, 
		monster = "The Weaver", 
		rarity = "Unique", 
	},
	{
		id = "UniqueNadiaTheSoothing", 
		min_level = 0, 
		monster = "Nadia the Soothing", 
		rarity = "Unique", 
	},
	{
		id = "UniqueAidanTheFrenzied", 
		min_level = 0, 
		monster = "Aidan the Frenzied", 
		rarity = "Unique", 
	},
	{
		id = "UniqueQuru", 
		min_level = 0, 
		monster = "Q'uru", 
		rarity = "Unique", 
	},
	{
		id = "UniqueThistlesage", 
		min_level = 0, 
		monster = "Thistlesage", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheConquerorWurm", 
		min_level = 0, 
		monster = "The Conqueror Wurm", 
		rarity = "Unique", 
	},
	{
		id = "UniqueParadisaeVenenum", 
		min_level = 0, 
		monster = "Paradisae Venenum", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheHundredFootShadow", 
		min_level = 0, 
		monster = "The Hundred Foot Shadow", 
		rarity = "Unique", 
	},
	{
		id = "UniqueEyepecker", 
		min_level = 0, 
		monster = "Eyepecker", 
		rarity = "Unique", 
	},
	{
		id = "UniqueSteelchaw", 
		min_level = 0, 
		monster = "Steelchaw", 
		rarity = "Unique", 
	},
	{
		id = "UniqueRaiharaTukohamasLoyal", 
		min_level = 0, 
		monster = "Raihara, Tukohama's Loyal", 
		rarity = "Unique", 
	},
	{
		id = "UniqueHollowskullTheWillingHost", 
		min_level = 0, 
		monster = "Hollowskull, the Willing Host", 
		rarity = "Unique", 
	},
	{
		id = "UniqueBrinecrack", 
		min_level = 0, 
		monster = "Brinecrack", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheGreatWhiteBones", 
		min_level = 0, 
		monster = "The Great White Bones", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTunnelworm", 
		min_level = 0, 
		monster = "Tunnelworm", 
		rarity = "Unique", 
	},
	{
		id = "UniqueBoulderback", 
		min_level = 0, 
		monster = "Boulderback", 
		rarity = "Unique", 
	},
	{
		id = "UniqueTheBasilisk", 
		min_level = 0, 
		monster = "The Basilisk", 
		rarity = "Unique", 
	},
	{
		id = "RareWithBestiaryMod1", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModBloodRaven1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod2", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModRootSpiderCascade1__", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod3", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModDaemonCorpseEruption", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod4", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModGraspingPincers1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod5", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModGoatmanAmbush1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod6", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModParasiticSquidVortex1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod7", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModSpiderCocoon1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod8", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModFire1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod9", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModIceFlowerFrog1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod10", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModSandLeaperExplode1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod11", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModSpiderExplode1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod12", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModStampede1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod13", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModScorpionBurrow1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod14", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModRavenStorm1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod15", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModSpiderAura1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod16", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModAgileRhexAura1_", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod17", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModVultureBomb1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod18", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModLynxAura1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod19", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModUrsaeAura1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod20", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModCrabAmbush1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod21", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModTigerRabbit1_", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod23", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModPouncingShade1", 
		rarity = "Rare", 
	},
	{
		id = "RareWithBestiaryMod24", 
		min_level = 0, 
		family = "Any Creature", 
		mod_id = "BestiaryModSquidAura1", 
		rarity = "Rare", 
	},
	{
		id = "SpiritBossTiger", 
		min_level = 0, 
		monster = "Farrul, First of the Plains", 
	},
	{
		id = "SpiritBossAvian", 
		min_level = 0, 
		monster = "Saqawal, First of the Sky", 
	},
	{
		id = "SpiritBossSpider", 
		min_level = 0, 
		monster = "Fenumus, First of the Night", 
	},
	{
		id = "SpiritBossCrab", 
		min_level = 0, 
		monster = "Craiceann, First of the Deep", 
	},
	{
		id = "Rhoa", 
		min_level = 0, 
		genus = "Rhoas", 
	},
	{
		id = "SeaWitch", 
		min_level = 0, 
		genus = "Sea Witches", 
	},
	{
		id = "ShieldCrab", 
		min_level = 0, 
		genus = "Shield Crabs", 
	},
	{
		id = "Goatman", 
		min_level = 0, 
		genus = "Goatmen", 
	},
	{
		id = "GoatShaman", 
		min_level = 0, 
		genus = "Goat Shamans", 
	},
	{
		id = "Hellion", 
		min_level = 0, 
		genus = "Hellions", 
	},
	{
		id = "MagicGargantuan", 
		min_level = 0, 
		genus = "Gargantuans", 
		rarity = "Magic", 
	},
	{
		id = "MagicSpider", 
		min_level = 0, 
		genus = "Spiders", 
		rarity = "Magic", 
	},
	{
		id = "MagicApe", 
		min_level = 0, 
		genus = "Apes", 
		rarity = "Magic", 
	},
	{
		id = "MagicPlummetingUrsa", 
		min_level = 0, 
		genus = "Plummeting Ursae", 
		rarity = "Magic", 
	},
	{
		id = "MagicGoliath", 
		min_level = 0, 
		genus = "Goliaths", 
		rarity = "Magic", 
	},
	{
		id = "MagicDevourer", 
		min_level = 0, 
		genus = "Devourers", 
		rarity = "Magic", 
	},
	{
		id = "MagicChimeral", 
		min_level = 0, 
		genus = "Chimerals", 
		rarity = "Magic", 
	},
	{
		id = "MagicVulture", 
		min_level = 0, 
		genus = "Vultures", 
		rarity = "Magic", 
	},
	{
		id = "MagicCockerel", 
		min_level = 0, 
		genus = "Cockerels", 
		rarity = "Magic", 
	},
	{
		id = "MagicPitbull", 
		min_level = 0, 
		genus = "Pitbulls", 
		rarity = "Magic", 
	},
	{
		id = "MagicKaruiHound", 
		min_level = 0, 
		genus = "Karui Hounds", 
		rarity = "Magic", 
	},
	{
		id = "MagicApeChieftain", 
		min_level = 0, 
		genus = "Ape Chieftains", 
		rarity = "Magic", 
	},
	{
		id = "RareLurcher", 
		min_level = 0, 
		genus = "Lurchers", 
		rarity = "Rare", 
	},
	{
		id = "RareGargantuan", 
		min_level = 0, 
		genus = "Gargantuans", 
		rarity = "Rare", 
	},
	{
		id = "RareDevourer", 
		min_level = 0, 
		genus = "Devourers", 
		rarity = "Rare", 
	},
	{
		id = "RareBull", 
		min_level = 0, 
		genus = "Bulls", 
		rarity = "Rare", 
	},
	{
		id = "RareChimeral", 
		min_level = 0, 
		genus = "Chimerals", 
		rarity = "Rare", 
	},
	{
		id = "AlbinoRhoa", 
		min_level = 0, 
		monster = "Albino Rhoa", 
	},
	{
		id = "Level70RareSeaWitchesWithBestiaryMod22", 
		min_level = 70, 
		genus = "Sea Witches", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareOctopusesWithBestiaryMod22", 
		min_level = 70, 
		genus = "Octopuses", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareLurcherWithBestiaryMod22", 
		min_level = 70, 
		genus = "Lurchers", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareMawWithBestiaryMod22", 
		min_level = 70, 
		genus = "Maws", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareAmphibianWithBestiaryMod22", 
		min_level = 70, 
		beast_group = "Amphibians", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareCrustaceanWithBestiaryMod22", 
		min_level = 70, 
		beast_group = "Crustaceans", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareCephalopodWithBestiaryMod22", 
		min_level = 70, 
		beast_group = "Cephalopods", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareUnnaturalWithBestiaryMod22", 
		min_level = 70, 
		beast_group = "Unnaturals", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareSandsWithBestiaryMod22", 
		min_level = 70, 
		family = "The Sands", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareDepthsWithBestiaryMod22", 
		min_level = 70, 
		family = "The Deep", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareCavernsWithBestiaryMod22", 
		min_level = 70, 
		family = "The Caverns", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareWildsWithBestiaryMod22", 
		min_level = 70, 
		family = "The Wilds", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareWatchersWithBestiaryMod22", 
		min_level = 70, 
		genus = "Watchers", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareGemFrogsWithBestiaryMod22", 
		min_level = 70, 
		genus = "Gem Frogs", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "RareWolf", 
		min_level = 0, 
		genus = "Wolves", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareDevourerWithBestiaryMod7", 
		min_level = 80, 
		genus = "Devourers", 
		mod_id = "BestiaryModSpiderCocoon1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareArachnoscorpionWithBestiaryMod13", 
		min_level = 80, 
		genus = "Arachnoscorpions", 
		mod_id = "BestiaryModScorpionBurrow1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareSpiderWithBestiaryMod11", 
		min_level = 80, 
		genus = "Spiders", 
		mod_id = "BestiaryModSpiderExplode1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareScorpionWithBestiaryMod15", 
		min_level = 80, 
		genus = "Scorpions", 
		mod_id = "BestiaryModSpiderAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareLeaperWithBestiaryMod10", 
		min_level = 80, 
		genus = "Leapers", 
		mod_id = "BestiaryModSandLeaperExplode1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareCarrionQueenWithBestiaryMod2", 
		min_level = 80, 
		genus = "Carrion Queens", 
		mod_id = "BestiaryModRootSpiderCascade1__", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareSeaWitchWithBestiaryMod9", 
		min_level = 80, 
		genus = "Sea Witches", 
		mod_id = "BestiaryModIceFlowerFrog1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareCrabWithBestiaryMod6", 
		min_level = 80, 
		genus = "Crabs", 
		mod_id = "BestiaryModParasiticSquidVortex1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareMawWithBestiaryMod24", 
		min_level = 80, 
		genus = "Maws", 
		mod_id = "BestiaryModSquidAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareSandSpitterWithBestiaryMod4", 
		min_level = 80, 
		genus = "Sand Spitters", 
		mod_id = "BestiaryModGraspingPincers1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareOctopusWithBestiaryMod22", 
		min_level = 80, 
		genus = "Octopuses", 
		mod_id = "BestiaryModCrabAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareSpawnWithBestiaryMod20", 
		min_level = 80, 
		genus = "Spawn", 
		mod_id = "BestiaryModCrabAmbush1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareChimeralWithBestiaryMod3", 
		min_level = 80, 
		genus = "Chimerals", 
		mod_id = "BestiaryModDaemonCorpseEruption", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareVultureWithBestiaryMod17", 
		min_level = 80, 
		genus = "Vultures", 
		mod_id = "BestiaryModVultureBomb1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareRetchWithBestiaryMod16", 
		min_level = 80, 
		genus = "Retches", 
		mod_id = "BestiaryModAgileRhexAura1_", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareSnakeWithBestiaryMod1", 
		min_level = 80, 
		genus = "Snakes", 
		mod_id = "BestiaryModBloodRaven1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareRhoaWithBestiaryMod14", 
		min_level = 80, 
		genus = "Rhoas", 
		mod_id = "BestiaryModRavenStorm1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareHellionWithBestiaryMod21", 
		min_level = 80, 
		genus = "Hellions", 
		mod_id = "BestiaryModTigerRabbit1_", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareGoatShamanWithBestiaryMod12", 
		min_level = 80, 
		genus = "Goat Shamans", 
		mod_id = "BestiaryModTigerRabbit1_", 
		rarity = "Rare", 
	},
	{
		id = "Level80RarePitbullWithBestiaryMod5", 
		min_level = 80, 
		genus = "Pitbulls", 
		mod_id = "BestiaryModGoatmanAmbush1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareGoliathWithBestiaryMod19", 
		min_level = 80, 
		genus = "Goliaths", 
		mod_id = "BestiaryModUrsaeAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareGargantuanWithBestiaryMod8", 
		min_level = 80, 
		genus = "Gargantuans", 
		mod_id = "BestiaryModFire1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareApeChieftainWithBestiaryMod18", 
		min_level = 80, 
		genus = "Ape Chieftains", 
		mod_id = "BestiaryModLynxAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level80RareKaruiHoundWithBestiaryMod23", 
		min_level = 80, 
		genus = "Karui Hounds", 
		mod_id = "BestiaryModPouncingShade1", 
		rarity = "Rare", 
	},
	{
		id = "Level78RareWolfWithBestiaryMod5", 
		min_level = 78, 
		genus = "Wolves", 
		mod_id = "BestiaryModGoatmanAmbush1", 
		rarity = "Rare", 
	},
	{
		id = "Level78RareWolfWithBestiaryMod18", 
		min_level = 78, 
		genus = "Wolves", 
		mod_id = "BestiaryModLynxAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level78RareWolfWithBestiaryMod21", 
		min_level = 78, 
		genus = "Wolves", 
		mod_id = "BestiaryModTigerRabbit1_", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareCephalopodWithBestiaryMod4", 
		min_level = 70, 
		beast_group = "Cephalopods", 
		mod_id = "BestiaryModGraspingPincers1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareDepthsWithBestiaryMod20", 
		min_level = 70, 
		family = "The Deep", 
		mod_id = "BestiaryModCrabAmbush1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareDepthsWithBestiaryMod6", 
		min_level = 70, 
		family = "The Deep", 
		mod_id = "BestiaryModParasiticSquidVortex1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareSnakeWithBestiaryMod1", 
		min_level = 70, 
		genus = "Snakes", 
		mod_id = "BestiaryModBloodRaven1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareGargantuansWithBestiaryMod18", 
		min_level = 70, 
		genus = "Gargantuans", 
		mod_id = "BestiaryModLynxAura1", 
		rarity = "Rare", 
	},
	{
		id = "Level70RareCarrionQueensWithBestiaryMod2", 
		min_level = 70, 
		genus = "Carrion Queens", 
		mod_id = "BestiaryModRootSpiderCascade1__", 
		rarity = "Rare", 
	},
	{
		id = "AnyRare", 
		min_level = 0, 
		family = "Any Creature", 
		rarity = "Rare", 
	},
	{
		id = "AnyRareLevel20Plus", 
		min_level = 20, 
		family = "Any Creature", 
		rarity = "Rare", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestBeastT3", 
		min_level = 0, 
		monster = "Wild Bristle Matron", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestHellionT3", 
		min_level = 0, 
		monster = "Wild Hellion Alpha", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestBrambleHulkT3", 
		min_level = 0, 
		monster = "Wild Brambleback", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestSquidT3", 
		min_level = 0, 
		monster = "Vivid Watcher", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestVultureParasiteT3", 
		min_level = 0, 
		monster = "Vivid Vulture", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestPlatedScorpionT3", 
		min_level = 0, 
		monster = "Vivid Abberarach", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestRhexT3", 
		min_level = 0, 
		monster = "Primal Rhex Matriarch", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestNessaCrabT3", 
		min_level = 0, 
		monster = "Primal Crushclaw", 
	},
	{
		id = "MemoryLineLegendaryBeastHarvestGoatmanT3", 
		min_level = 0, 
		monster = "Primal Cystcaller", 
	}}
return data