local data = {	{
		id = "EinharMasterCraft1", 
		header = "Create Currency Items", 
		subheader = "A Stack of 8 Chromatic Orbs", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft2", 
		header = "Create Currency Items", 
		subheader = "A Stack of 4 Jeweller's Orbs", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft3", 
		header = "Create Currency Items", 
		subheader = "Orb of Fusing", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft4", 
		header = "Create a Unique", 
		subheader = "Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft5", 
		header = "Create a Unique", 
		subheader = "Ring", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft6", 
		header = "Create a Unique", 
		subheader = "Amulet", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft7", 
		header = "Create a Unique", 
		subheader = "Belt", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft8", 
		header = "Create a Unique", 
		subheader = "Flask", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft9", 
		header = "Create a Unique", 
		subheader = "Helmet", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft10", 
		header = "Create a Unique", 
		subheader = "Body Armour", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft11", 
		header = "Create a Unique", 
		subheader = "Boots", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft12", 
		header = "Create a Unique", 
		subheader = "Gloves", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft13", 
		header = "Create a Rare", 
		subheader = "Talisman", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft14", 
		header = "Create a Unique", 
		subheader = "Claw or Dagger", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft15", 
		header = "Create a Unique", 
		subheader = "Mace or Sceptre", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft16", 
		header = "Create a Unique", 
		subheader = "Shield or Quiver", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft17", 
		header = "Create a Unique", 
		subheader = "Sword or Axe", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft18", 
		header = "Create a Unique", 
		subheader = "Staff", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft20", 
		header = "Create a Unique", 
		subheader = "Bow", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft21", 
		header = "Create a Unique", 
		subheader = "Wand", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft22", 
		header = "Create a Unique", 
		subheader = "Map", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft23", 
		header = "Create an Item", 
		subheader = "23% Quality Corrupted Gem", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft24", 
		header = "Create an Item", 
		subheader = "Level 21 Corrupted Gem", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft25", 
		header = "Create an Item", 
		subheader = "Fully-linked Six-socket Rare", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft26", 
		header = "Create Currency Items", 
		subheader = "A Stack of 10 Random Currency", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft27", 
		header = "Create an Imprint", 
		subheader = "Of a Magic Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft28", 
		header = "Corrupt a Map", 
		subheader = "To have 30% Quality", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft29", 
		header = "Transform an Item", 
		subheader = "from an Amulet into a Talisman", 
		notes = "Does not work on Influenced items", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft30", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Suffix, Remove a Random Prefix", 
		notes = "Only works on rare items", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft31", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Prefix, Remove a Random Suffix", 
		notes = "Only works on rare items", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft32", 
		header = "Split an Item", 
		subheader = "Into Two Items, with Half the Mods on Each Item", 
		notes = "Does not work on Influenced or Split items", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft33", 
		header = "Convert this Unique Item", 
		subheader = "Into Another Random Unique Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask1", 
		header = "Add a Mod to a Life or Mana Flask", 
		subheader = "Adds \"of Convection\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask2", 
		header = "Add a Mod to a Life or Mana Flask", 
		subheader = "Adds \"of Damping\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask3", 
		header = "Add a Mod to a Life or Mana Flask", 
		subheader = "Adds \"of Sealing\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask4", 
		header = "Add a Mod to a Life or Mana Flask", 
		subheader = "Adds \"of Earthing\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask5", 
		header = "Add a Mod to a Life or Mana Flask", 
		subheader = "Adds \"of the Antitoxin\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask6", 
		header = "Add a Mod to a Life or Mana Flask", 
		subheader = "Adds \"of Warding\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask7", 
		header = "Add a Mod to a Utility Flask", 
		subheader = "Adds \"of the Lizard\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask8", 
		header = "Add a Mod to a Utility Flask", 
		subheader = "Adds \"of the Skunk\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask9", 
		header = "Add a Mod to a Utility Flask", 
		subheader = "Adds \"of the Conger\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask10", 
		header = "Add a Mod to a Utility Flask", 
		subheader = "Adds \"of the Deer\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftFlask11", 
		header = "Add a Mod to a Utility Flask", 
		subheader = "Adds \"of the Urchin\"", 
		notes = "Requires Flask to have no existing Suffix", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft34", 
		header = "Open a Portal", 
		subheader = "to Farrul's Den", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft35", 
		header = "Open a Portal", 
		subheader = "to Saqawal's Roost", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft36", 
		header = "Open a Portal", 
		subheader = "to Fenumus' Lair", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft37", 
		header = "Open a Portal", 
		subheader = "to Craiceann's Cove", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft38", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Aspect of the Cat skill", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft39", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Aspect of the Avian skill", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft40", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Aspect of the Spider skill", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft41", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Aspect of the Crab skill", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft42", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Mod to a Shaper Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft43", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Mod to an Elder Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft44", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Mod to a Redeemer Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft45", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Mod to a Hunter Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft46", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Mod to a Crusader Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft47", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Mod to a Warlord Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft48", 
		header = "Corrupt a Map", 
		subheader = "Twice", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft49", 
		header = "Modify Mods on an Item", 
		subheader = "Add a Mod to a Rare Map", 
		notes = "Only works on rare maps", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft50", 
		header = "Create Currency Items", 
		subheader = "A Stack of 2 Orbs of Binding", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraft51", 
		header = "Create Currency Items", 
		subheader = "A Stack of 3 Orbs of Horizons", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine1", 
		header = "Modify Mods on an Item", 
		subheader = "Add a crafted Meta-modifier to a non-Unique Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine2", 
		header = "Modify Mods on an Item", 
		subheader = "Reroll a Watcher's Eye Modifier", 
		notes = "Cannot reroll Maximum Life, Mana or Energy Shield modifiers", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine3", 
		header = "Transform an Item", 
		subheader = "Increase level of non-Corrupted Awakened Gem by 1", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine4", 
		header = "Transform an Item", 
		subheader = "Reroll an Awakened Support Gem", 
		notes = "Cannot result in Awakened Empower, Enhance or Enlighten", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine5", 
		header = "Transform an Item", 
		subheader = "Reroll a Synthesis Implicit Modifier", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine6", 
		header = "Create an Item", 
		subheader = "Shaper Guardian, Elder Guardian or Conqueror Map", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine7", 
		header = "Create an Item", 
		subheader = "Synthesis Unique Map", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine8", 
		header = "Gain Atlas Crafts", 
		subheader = "Gain a free use of each Map Crafting Option", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMemoryLine9", 
		header = "Gain Atlas Crafts", 
		subheader = "Gain Five Kirac Missions", 
		notes = "Colour of Missions based on Level of Red Beast", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftHardModeFlask1", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when an adjacent Flask is used\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask2", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Reused at the end of this Flask's effect\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask3", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when Charges reach full\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask4", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you Use a Guard Skill\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask5", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you Use a Travel Skill\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask6", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you Hit a Rare or Unique Enemy, if not already in effect\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask7", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you become Frozen\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask8", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you become Chilled\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask9", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you become Shocked\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask10", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you become Ignited\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask11", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you start Bleeding\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask12", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you become Poisoned\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask13", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you Block\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask14", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you take a Savage Hit\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftHardModeFlask15", 
		header = "Enchant a Utility Flask", 
		subheader = "Adds \"Used when you use a Life Flask\"", 
		notes = "Replaces any existing Enchantment", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft1HardMode", 
		header = "Create a Talisman", 
		subheader = "Breakrib Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft2HardMode", 
		header = "Create a Talisman", 
		subheader = "Ashscale Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft3HardMode", 
		header = "Create a Talisman", 
		subheader = "Lone Antler Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft4HardMode", 
		header = "Create a Talisman", 
		subheader = "Deep One Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft5HardMode", 
		header = "Create a Talisman", 
		subheader = "Chrysalis Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft6HardMode", 
		header = "Create a Talisman", 
		subheader = "Writhing Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft7HardMode", 
		header = "Create a Talisman", 
		subheader = "Mandible Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft8HardMode", 
		header = "Create a Talisman", 
		subheader = "Bonespire Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft9HardMode", 
		header = "Create a Talisman", 
		subheader = "Deadhand Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft10HardMode", 
		header = "Create a Talisman", 
		subheader = "Undying Flesh Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft11HardMode", 
		header = "Create a Talisman", 
		subheader = "Black Maw Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft12HardMode", 
		header = "Create a Talisman", 
		subheader = "Splitnewt Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft13HardMode", 
		header = "Create a Talisman", 
		subheader = "Clutching Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft14HardMode", 
		header = "Create a Talisman", 
		subheader = "Horned Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft15HardMode", 
		header = "Create a Talisman", 
		subheader = "Primal Skull Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft16HardMode", 
		header = "Create a Talisman", 
		subheader = "Hexclaw Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft17HardMode", 
		header = "Create a Talisman", 
		subheader = "Fangjaw Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft18HardMode", 
		header = "Create a Talisman", 
		subheader = "Wereclaw Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft19HardMode", 
		header = "Create a Talisman", 
		subheader = "Monkey Twins Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft20HardMode", 
		header = "Create a Talisman", 
		subheader = "Three Hands Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft21HardMode", 
		header = "Create a Talisman", 
		subheader = "Longtooth Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft22HardMode", 
		header = "Create a Talisman", 
		subheader = "Rotfeather Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft23HardMode", 
		header = "Create a Talisman", 
		subheader = "Three Rat Talisman", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft24HardMode", 
		header = "Create a Talisman", 
		subheader = "Avian Twins Talisman (Fire)", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft25HardMode", 
		header = "Create a Talisman", 
		subheader = "Avian Twins Talisman (Lightning)", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft26HardMode", 
		header = "Create a Talisman", 
		subheader = "Avian Twins Talisman (Cold)", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft27HardMode", 
		header = "Create a Talisman", 
		subheader = "Monkey Paw Talisman (Power)", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft28HardMode", 
		header = "Create a Talisman", 
		subheader = "Monkey Paw Talisman (Frenzy)", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft29HardMode", 
		header = "Create a Talisman", 
		subheader = "Monkey Paw Talisman (Endurance)", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft30HardMode", 
		header = "Transform an Item", 
		subheader = "from an Amulet into a Talisman", 
		notes = "Does not work on Influenced items", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft31HardMode", 
		header = "Create an Imprint", 
		subheader = "Of a Magic Item", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft32HardMode", 
		header = "Corrupt a Map", 
		subheader = "To have 30% Quality", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft33HardMode", 
		header = "Convert this Unique Item", 
		subheader = "Into Another Random Unique Item", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft34HardMode", 
		header = "Corrupt a Map", 
		subheader = "Twice", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft35HardMode", 
		header = "Open a Portal", 
		subheader = "to Farrul's Den", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft36HardMode", 
		header = "Open a Portal", 
		subheader = "to Saqawal's Roost", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft37HardMode", 
		header = "Open a Portal", 
		subheader = "to Fenumus' Lair", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft38HardMode", 
		header = "Open a Portal", 
		subheader = "to Craiceann's Cove", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft39HardMode", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 20 Aspect of the Cat skill", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft40HardMode", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 20 Aspect of the Avian skill", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft41HardMode", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 20 Aspect of the Spider skill", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraft42HardMode", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 20 Aspect of the Crab skill", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftMorrigan1", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 30 Aspect of the Cat skill", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMorrigan2", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 30 Aspect of the Avian skill", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMorrigan3", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 30 Aspect of the Spider skill", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMorrigan4", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 30 Aspect of the Crab skill", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMorrigan5", 
		header = "Apply a Hinekora's Lock", 
		subheader = "To a Magic Item", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMorrigan6", 
		header = "Split an Item", 
		subheader = "Into Three Items, with Two Mods on Each Item", 
		notes = "Does not work on Influenced or Split items", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMorrigan7", 
		header = "Modify an Item", 
		subheader = "to Have Maximum Possible Links", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMorrigan8", 
		header = "Modify an Item", 
		subheader = "to Have Maximum Possible Number of Sockets", 
		game_mode = 1, 
	},
	{
		id = "EinharMasterCraftMorrigan1HardMode", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 30 Aspect of the Cat skill", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftMorrigan2HardMode", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 30 Aspect of the Avian skill", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftMorrigan3HardMode", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 30 Aspect of the Spider skill", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftMorrigan4HardMode", 
		header = "Craft an Aspect Skill onto an Item", 
		subheader = "Level 30 Aspect of the Crab skill", 
		game_mode = 2, 
	},
	{
		id = "EinharMasterCraftMorrigan5HardMode", 
		header = "Apply a Hinekora's Lock", 
		subheader = "To a Magic Item", 
		game_mode = 2, 
	}}
return data