local data = {	{
		name = "Character", 
		id = "level", 
		value = 1, 
		stat_text = "[[Level]] 1", 
	},
	{
		name = "Character", 
		id = "is_player", 
		value = 1, 
		stat_text = "Is player", 
	},
	{
		name = "Character", 
		id = "energy_shield_recharge_rate_per_minute_%", 
		value = 2000, 
		stat_text = "33.3% of [[Energy Shield]] Recharged per second", 
	},
	{
		name = "Character", 
		id = "mana_regeneration_rate_per_minute_%", 
		value = 105, 
		stat_text = "Regenerate 1.8% of [[Mana]] per second", 
	},
	{
		name = "Character", 
		id = "base_maximum_all_resistances_%", 
		value = 75, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "maximum_physical_damage_reduction_%", 
		value = 90, 
		stat_text = "90% to maximum [[Physical Damage]] Reduction", 
	},
	{
		name = "Character", 
		id = "maximum_block_%", 
		value = 75, 
		stat_text = "+75% to maximum Chance to [[Block]] [[Attack Damage]]", 
	},
	{
		name = "Character", 
		id = "base_maximum_spell_block_%", 
		value = 75, 
		stat_text = "+75% to maximum Chance to [[Block]] [[Spell Damage]]", 
	},
	{
		name = "Character", 
		id = "base_attack_speed_+%_per_frenzy_charge", 
		value = 4, 
		stat_text = "4% increased [[Attack Speed]] per [[Frenzy Charge]]", 
	},
	{
		name = "Character", 
		id = "base_cast_speed_+%_per_frenzy_charge", 
		value = 4, 
		stat_text = "4% increased [[Cast Speed]] per [[Frenzy Charge]]", 
	},
	{
		name = "Character", 
		id = "object_inherent_damage_+%_final_per_frenzy_charge", 
		value = 4, 
		stat_text = "4% more Damage per [[Frenzy Charge]]", 
	},
	{
		name = "Character", 
		id = "physical_damage_reduction_%_per_endurance_charge", 
		value = 4, 
		stat_text = "4% additional [[Physical Damage]] Reduction per [[Endurance Charge]]", 
	},
	{
		name = "Character", 
		id = "resist_all_elements_%_per_endurance_charge", 
		value = 4, 
		stat_text = "+4% to all [[Elemental Resistance|Elemental Resistances]] per [[Endurance Charge]]", 
	},
	{
		name = "Character", 
		id = "critical_strike_chance_+%_per_power_charge", 
		value = 50, 
		stat_text = "50% increased [[Critical Strike Chance]] per [[Power Charge]]", 
	},
	{
		name = "Character", 
		id = "max_viper_strike_orbs", 
		value = 4, 
		stat_text = "Can have up to 4 [[Viper Strike]] Orbs", 
	},
	{
		name = "Character", 
		id = "dual_wield_inherent_attack_speed_+%_final", 
		value = 10, 
		stat_text = "10% more [[Attack Speed]] while [[Dual Wield|Dual Wielding]]", 
	},
	{
		name = "Character", 
		id = "max_fuse_arrow_orbs", 
		value = 5, 
		stat_text = "Can have up to 5 [[Explosive Arrow]] Stacks", 
	},
	{
		name = "Character", 
		id = "max_fire_beam_stacks", 
		value = 8, 
		stat_text = "Can have up to 8 Fire Beam Stacks", 
	},
	{
		name = "Character", 
		id = "base_evasion_rating", 
		value = 15, 
		stat_text = "+15 to [[Evasion Rating]]", 
	},
	{
		name = "Character", 
		id = "life_per_level", 
		value = 12, 
		stat_text = "+12 Maximum [[Life]] per [[Level]]", 
	},
	{
		name = "Character", 
		id = "mana_per_level", 
		value = 6, 
		stat_text = "+6 Maximum [[Mana]] per [[Level]]", 
	},
	{
		name = "Character", 
		id = "accuracy_rating_per_level", 
		value = 2, 
		stat_text = "+2 [[Accuracy Rating]] per [[Level]]", 
	},
	{
		name = "Character", 
		id = "inherent_block_while_dual_wielding_%", 
		value = 15, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "base_critical_strike_multiplier", 
		value = 150, 
		stat_text = "Base [[Critical Strike]] Multiplier: 150", 
	},
	{
		name = "Character", 
		id = "critical_ailment_dot_multiplier_+", 
		value = 50, 
		stat_text = "+50% to Damage over Time Multiplier for Ailments from Critical Strikes", 
	},
	{
		name = "Character", 
		id = "max_endurance_charges", 
		value = 3, 
		stat_text = "+3 to Maximum [[Endurance Charge|Endurance Charges]]", 
	},
	{
		name = "Character", 
		id = "max_frenzy_charges", 
		value = 3, 
		stat_text = "+3 to Maximum [[Frenzy Charge|Frenzy Charges]]", 
	},
	{
		name = "Character", 
		id = "max_power_charges", 
		value = 3, 
		stat_text = "+3 to Maximum [[Power Charge|Power Charges]]", 
	},
	{
		name = "Character", 
		id = "maximum_righteous_charges", 
		value = 5, 
		stat_text = "Can have up to 5 Righteous [[Charge|Charges]]", 
	},
	{
		name = "Character", 
		id = "maximum_blood_scythe_charges", 
		value = 5, 
		stat_text = "+5 to Maximum Blood [[Charge|Charges]]", 
	},
	{
		name = "Character", 
		id = "base_number_of_totems_allowed", 
		value = 1, 
		stat_text = "+1 to maximum number of Summoned [[Totem|Totems]]", 
	},
	{
		name = "Character", 
		id = "base_number_of_traps_allowed", 
		value = 15, 
		stat_text = "Can have up to 15 [[Trap|Traps]] placed at a time", 
	},
	{
		name = "Character", 
		id = "base_number_of_remote_mines_allowed", 
		value = 15, 
		stat_text = "Can have up to 15 Remote [[Mine|Mines]] placed at a time", 
	},
	{
		name = "Character", 
		id = "max_charged_attack_stacks", 
		value = 6, 
		stat_text = "6 additional maximum [[Blade Flurry]] stages", 
	},
	{
		name = "Character", 
		id = "max_talisman_degen_stacks", 
		value = 20, 
		stat_text = "Can have up to 20 Talisman degen Stacks", 
	},
	{
		name = "Character", 
		id = "max_frost_nova_stacks", 
		value = 20, 
		stat_text = "Can have up to 20 Frost Nova Stacks", 
	},
	{
		name = "Character", 
		id = "max_rampage_stacks", 
		value = 1000, 
		stat_text = "Can have up to 1000 [[Rampage]] Stacks", 
	},
	{
		name = "Character", 
		id = "damage_+%_per_10_rampage_stacks", 
		value = 2, 
		stat_text = "2% increased Damage per 20 [[Rampage]] Stacks", 
	},
	{
		name = "Character", 
		id = "movement_velocity_+%_per_10_rampage_stacks", 
		value = 1, 
		stat_text = "1% increased [[Movement Speed]] per 20 [[Rampage]] Stacks", 
	},
	{
		name = "Character", 
		id = "pvp_shield_damage_+%_final", 
		value = -15, 
		stat_text = "15% less [[Shield]] Damage in [[PvP]]", 
	},
	{
		name = "Character", 
		id = "maximum_life_leech_rate_%_per_minute", 
		value = 1200, 
		stat_text = "+20% to Maximum total [[Life]] Recovery per second from [[Leech]]", 
	},
	{
		name = "Character", 
		id = "maximum_mana_leech_rate_%_per_minute", 
		value = 1200, 
		stat_text = "+20% Maximum total [[Mana]] Recovery per second from [[Leech]]", 
	},
	{
		name = "Character", 
		id = "maximum_energy_shield_leech_rate_%_per_minute", 
		value = 600, 
		stat_text = "+10% to Maximum total [[Energy Shield]] Recovery per second from [[Leech]]", 
	},
	{
		name = "Character", 
		id = "minions_have_labyrinth_trap_degen_effect_+%", 
		value = -90, 
		stat_text = "[[Minion|Minions]] take 90% less Damage over Time by Labyrinth [[Trap|Traps]]", 
	},
	{
		name = "Character", 
		id = "minion_damage_taken_+%_from_spike_traps_final", 
		value = -90, 
		stat_text = "[[Minion|Minions]] take 90% less Damage from Spike [[Trap|Traps]]", 
	},
	{
		name = "Character", 
		id = "minion_damage_taken_+%_from_guillotine_traps_final", 
		value = -90, 
		stat_text = "[[Minion|Minions]] take 90% less Damage from Guillotine [[Trap|Traps]]", 
	},
	{
		name = "Character", 
		id = "traps_explode_on_timeout", 
		value = 1, 
		stat_text = "[[Trap|Traps]] Trigger at the end of their Duration", 
	},
	{
		name = "Character", 
		id = "maximum_rage", 
		value = 50, 
		stat_text = "+50 to Maximum Rage", 
	},
	{
		name = "Character", 
		id = "max_delve_degen_stacks", 
		value = 5000, 
		stat_text = "Can have up to 5000 Darkness Stacks", 
	},
	{
		name = "Character", 
		id = "max_azurite_debuff_stacks", 
		value = 10, 
		stat_text = "Can have up to 10 Azurite Stacks", 
	},
	{
		name = "Character", 
		id = "melee_variation", 
		value = 1, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "impaled_debuff_base_duration_ms", 
		value = 8000, 
		stat_text = "Impale lasts 8 seconds", 
	},
	{
		name = "Character", 
		id = "impaled_debuff_number_of_reflected_hits", 
		value = 5, 
		stat_text = "Impales you inflict last 5 additional [[Hit|Hits]]", 
	},
	{
		name = "Character", 
		id = "base_total_number_of_sigils_allowed", 
		value = 3, 
		stat_text = "You can Cast 3 additional Brands", 
	},
	{
		name = "Character", 
		id = "maximum_life_leech_amount_per_leech_%_max_life", 
		value = 10, 
		stat_text = "+10% of Maximum [[Life]] to maximum Recovery per [[Life]] [[Leech]]", 
	},
	{
		name = "Character", 
		id = "maximum_mana_leech_amount_per_leech_%_max_mana", 
		value = 10, 
		stat_text = "+10% of Maximum [[Mana]] to maximum Recovery per [[Mana]] [[Leech]]", 
	},
	{
		name = "Character", 
		id = "maximum_energy_shield_leech_amount_per_leech_%_max_energy_shield", 
		value = 10, 
		stat_text = "+10% of Maximum [[Energy Shield]] to maximum Recovery per [[Energy Shield]] [[Leech]]", 
	},
	{
		name = "Character", 
		id = "enable_movement_skill_animation_skipping", 
		value = 1, 
		stat_text = "Movement [[Skill|skill]] animations can be skipped", 
	},
	{
		name = "Character", 
		id = "melee_hit_damage_stun_multiplier_+%", 
		value = 25, 
		stat_text = "Melee Damage counts as 25% more for Stuns", 
	},
	{
		name = "Character", 
		id = "non_physical_hit_damage_stun_multiplier_+%", 
		value = -25, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "non_melee_hit_damage_stun_multiplier_+%_final", 
		value = -25, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "object_inherent_melee_hit_stun_duration_+%_final", 
		value = 50, 
		stat_text = "Melee [[Hit|hits]] have 50% more Stun Duration", 
	},
	{
		name = "Character", 
		id = "additional_insanity_effects_while_delirious", 
		value = 1, 
		stat_text = "Insanity effects while delirious", 
	},
	{
		name = "Character", 
		id = "max_steel_ammo", 
		value = 12, 
		stat_text = "Call of Steel has +12 to maximum Steel Shards", 
	},
	{
		name = "Character", 
		id = "chance_to_deal_triple_damage_%_per_brutal_charge", 
		value = 3, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "stun_threshold_+%_per_brutal_charge", 
		value = 10, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "ailment_damage_+%_final_per_affliction_charge", 
		value = 8, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "non_damaging_ailment_effect_+%_final_per_affliction_charge", 
		value = 8, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "elemental_damage_taken_goes_to_energy_shield_over_4_seconds_%_per_absorption_charge", 
		value = 12, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "actor_scale_+%_limit", 
		value = 100, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "mines_invulnerable_for_duration_ms", 
		value = 2000, 
		stat_text = "[[Mine|Mines]] cannot be Damaged for +2 seconds after being thrown", 
	},
	{
		name = "Character", 
		id = "traps_invulnerable_for_duration_ms", 
		value = 2000, 
		stat_text = "[[Trap|Traps]] cannot be Damaged for +2 seconds after being Thrown", 
	},
	{
		name = "Character", 
		id = "damage_taken_when_hit_+%_final_per_fortification", 
		value = -1, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "base_max_fortification", 
		value = 20, 
		stat_text = "+20 to maximum Fortification", 
	},
	{
		name = "Character", 
		id = "base_presence_radius", 
		value = 80, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "mtx_max_killstreak_stacks", 
		value = 1000, 
		stat_text = "", 
	},
	{
		name = "Character", 
		id = "mtx_max_killcounter_stacks", 
		value = 30000, 
		stat_text = "", 
	}}
return data