local data = {	{
		type = "sulphite_capacity", 
		level = 0, 
		id = "delve_sulphite_capacity", 
		value = 1200, 
	},
	{
		type = "sulphite_capacity", 
		level = 1, 
		id = "delve_sulphite_capacity", 
		value = 1800, 
	},
	{
		type = "sulphite_capacity", 
		level = 2, 
		id = "delve_sulphite_capacity", 
		value = 2400, 
	},
	{
		type = "sulphite_capacity", 
		level = 3, 
		id = "delve_sulphite_capacity", 
		value = 3000, 
	},
	{
		type = "sulphite_capacity", 
		level = 4, 
		id = "delve_sulphite_capacity", 
		value = 4000, 
	},
	{
		type = "sulphite_capacity", 
		level = 5, 
		id = "delve_sulphite_capacity", 
		value = 5200, 
	},
	{
		type = "sulphite_capacity", 
		level = 6, 
		id = "delve_sulphite_capacity", 
		value = 6400, 
	},
	{
		type = "sulphite_capacity", 
		level = 7, 
		id = "delve_sulphite_capacity", 
		value = 9000, 
	},
	{
		type = "sulphite_capacity", 
		level = 8, 
		id = "delve_sulphite_capacity", 
		value = 12500, 
	},
	{
		type = "sulphite_capacity", 
		level = 9, 
		id = "delve_sulphite_capacity", 
		value = 17500, 
	},
	{
		type = "sulphite_capacity", 
		level = 10, 
		id = "delve_sulphite_capacity", 
		value = 22750, 
	},
	{
		type = "sulphite_capacity", 
		level = 11, 
		id = "delve_sulphite_capacity", 
		value = 30000, 
	},
	{
		type = "sulphite_capacity", 
		level = 12, 
		id = "delve_sulphite_capacity", 
		value = 38500, 
	},
	{
		type = "sulphite_capacity", 
		level = 13, 
		id = "delve_sulphite_capacity", 
		value = 46000, 
	},
	{
		type = "sulphite_capacity", 
		level = 14, 
		id = "delve_sulphite_capacity", 
		value = 55000, 
	},
	{
		type = "sulphite_capacity", 
		level = 15, 
		id = "delve_sulphite_capacity", 
		value = 65000, 
	},
	{
		type = "flare_capacity", 
		level = 0, 
		id = "delve_flare_capacity", 
		value = 3, 
	},
	{
		type = "flare_capacity", 
		level = 1, 
		id = "delve_flare_capacity", 
		value = 4, 
	},
	{
		type = "flare_capacity", 
		level = 2, 
		id = "delve_flare_capacity", 
		value = 5, 
	},
	{
		type = "flare_capacity", 
		level = 3, 
		id = "delve_flare_capacity", 
		value = 6, 
	},
	{
		type = "flare_capacity", 
		level = 4, 
		id = "delve_flare_capacity", 
		value = 7, 
	},
	{
		type = "flare_capacity", 
		level = 5, 
		id = "delve_flare_capacity", 
		value = 8, 
	},
	{
		type = "flare_capacity", 
		level = 6, 
		id = "delve_flare_capacity", 
		value = 9, 
	},
	{
		type = "flare_capacity", 
		level = 7, 
		id = "delve_flare_capacity", 
		value = 10, 
	},
	{
		type = "flare_capacity", 
		level = 8, 
		id = "delve_flare_capacity", 
		value = 11, 
	},
	{
		type = "flare_capacity", 
		level = 9, 
		id = "delve_flare_capacity", 
		value = 12, 
	},
	{
		type = "flare_capacity", 
		level = 10, 
		id = "delve_flare_capacity", 
		value = 13, 
	},
	{
		type = "flare_capacity", 
		level = 11, 
		id = "delve_flare_capacity", 
		value = 14, 
	},
	{
		type = "flare_capacity", 
		level = 12, 
		id = "delve_flare_capacity", 
		value = 15, 
	},
	{
		type = "flare_capacity", 
		level = 13, 
		id = "delve_flare_capacity", 
		value = 16, 
	},
	{
		type = "flare_capacity", 
		level = 14, 
		id = "delve_flare_capacity", 
		value = 17, 
	},
	{
		type = "flare_capacity", 
		level = 15, 
		id = "delve_flare_capacity", 
		value = 18, 
	},
	{
		type = "flare_capacity", 
		level = 16, 
		id = "delve_flare_capacity", 
		value = 19, 
	},
	{
		type = "flare_capacity", 
		level = 17, 
		id = "delve_flare_capacity", 
		value = 20, 
	},
	{
		type = "dynamite_capacity", 
		level = 0, 
		id = "delve_dynamite_capacity", 
		value = 2, 
	},
	{
		type = "dynamite_capacity", 
		level = 1, 
		id = "delve_dynamite_capacity", 
		value = 3, 
	},
	{
		type = "dynamite_capacity", 
		level = 2, 
		id = "delve_dynamite_capacity", 
		value = 4, 
	},
	{
		type = "dynamite_capacity", 
		level = 3, 
		id = "delve_dynamite_capacity", 
		value = 5, 
	},
	{
		type = "dynamite_capacity", 
		level = 4, 
		id = "delve_dynamite_capacity", 
		value = 6, 
	},
	{
		type = "dynamite_capacity", 
		level = 5, 
		id = "delve_dynamite_capacity", 
		value = 7, 
	},
	{
		type = "light_radius", 
		level = 0, 
		id = "delve_light_radius_+%", 
		value = 0, 
	},
	{
		type = "light_radius", 
		level = 1, 
		id = "delve_light_radius_+%", 
		value = 30, 
	},
	{
		type = "light_radius", 
		level = 2, 
		id = "delve_light_radius_+%", 
		value = 60, 
	},
	{
		type = "light_radius", 
		level = 3, 
		id = "delve_light_radius_+%", 
		value = 90, 
	},
	{
		type = "light_radius", 
		level = 4, 
		id = "delve_light_radius_+%", 
		value = 120, 
	},
	{
		type = "light_radius", 
		level = 5, 
		id = "delve_light_radius_+%", 
		value = 150, 
	},
	{
		type = "light_radius", 
		level = 6, 
		id = "delve_light_radius_+%", 
		value = 180, 
	},
	{
		type = "light_radius", 
		level = 7, 
		id = "delve_light_radius_+%", 
		value = 210, 
	},
	{
		type = "light_radius", 
		level = 8, 
		id = "delve_light_radius_+%", 
		value = 240, 
	},
	{
		type = "light_radius", 
		level = 9, 
		id = "delve_light_radius_+%", 
		value = 270, 
	},
	{
		type = "light_radius", 
		level = 10, 
		id = "delve_light_radius_+%", 
		value = 300, 
	},
	{
		type = "light_radius", 
		level = 11, 
		id = "delve_light_radius_+%", 
		value = 330, 
	},
	{
		type = "light_radius", 
		level = 12, 
		id = "delve_light_radius_+%", 
		value = 360, 
	},
	{
		type = "light_radius", 
		level = 13, 
		id = "delve_light_radius_+%", 
		value = 390, 
	},
	{
		type = "light_radius", 
		level = 14, 
		id = "delve_light_radius_+%", 
		value = 420, 
	},
	{
		type = "light_radius", 
		level = 15, 
		id = "delve_light_radius_+%", 
		value = 450, 
	},
	{
		type = "light_radius", 
		level = 16, 
		id = "delve_light_radius_+%", 
		value = 480, 
	},
	{
		type = "light_radius", 
		level = 17, 
		id = "delve_light_radius_+%", 
		value = 510, 
	},
	{
		type = "light_radius", 
		level = 18, 
		id = "delve_light_radius_+%", 
		value = 540, 
	},
	{
		type = "light_radius", 
		level = 19, 
		id = "delve_light_radius_+%", 
		value = 570, 
	},
	{
		type = "light_radius", 
		level = 20, 
		id = "delve_light_radius_+%", 
		value = 600, 
	},
	{
		type = "light_radius", 
		level = 21, 
		id = "delve_light_radius_+%", 
		value = 630, 
	},
	{
		type = "light_radius", 
		level = 22, 
		id = "delve_light_radius_+%", 
		value = 660, 
	},
	{
		type = "light_radius", 
		level = 23, 
		id = "delve_light_radius_+%", 
		value = 690, 
	},
	{
		type = "light_radius", 
		level = 24, 
		id = "delve_light_radius_+%", 
		value = 720, 
	},
	{
		type = "light_radius", 
		level = 25, 
		id = "delve_light_radius_+%", 
		value = 750, 
	},
	{
		type = "light_radius", 
		level = 26, 
		id = "delve_light_radius_+%", 
		value = 780, 
	},
	{
		type = "light_radius", 
		level = 27, 
		id = "delve_light_radius_+%", 
		value = 810, 
	},
	{
		type = "light_radius", 
		level = 28, 
		id = "delve_light_radius_+%", 
		value = 840, 
	},
	{
		type = "light_radius", 
		level = 29, 
		id = "delve_light_radius_+%", 
		value = 870, 
	},
	{
		type = "light_radius", 
		level = 30, 
		id = "delve_light_radius_+%", 
		value = 900, 
	},
	{
		type = "light_radius", 
		level = 31, 
		id = "delve_light_radius_+%", 
		value = 930, 
	},
	{
		type = "light_radius", 
		level = 32, 
		id = "delve_light_radius_+%", 
		value = 960, 
	},
	{
		type = "light_radius", 
		level = 33, 
		id = "delve_light_radius_+%", 
		value = 990, 
	},
	{
		type = "light_radius", 
		level = 34, 
		id = "delve_light_radius_+%", 
		value = 1020, 
	},
	{
		type = "light_radius", 
		level = 35, 
		id = "delve_light_radius_+%", 
		value = 1050, 
	},
	{
		type = "light_radius", 
		level = 36, 
		id = "delve_light_radius_+%", 
		value = 1080, 
	},
	{
		type = "light_radius", 
		level = 37, 
		id = "delve_light_radius_+%", 
		value = 1110, 
	},
	{
		type = "light_radius", 
		level = 38, 
		id = "delve_light_radius_+%", 
		value = 1140, 
	},
	{
		type = "light_radius", 
		level = 39, 
		id = "delve_light_radius_+%", 
		value = 1170, 
	},
	{
		type = "light_radius", 
		level = 40, 
		id = "delve_light_radius_+%", 
		value = 1200, 
	},
	{
		type = "light_radius", 
		level = 41, 
		id = "delve_light_radius_+%", 
		value = 1230, 
	},
	{
		type = "light_radius", 
		level = 42, 
		id = "delve_light_radius_+%", 
		value = 1260, 
	},
	{
		type = "light_radius", 
		level = 43, 
		id = "delve_light_radius_+%", 
		value = 1290, 
	},
	{
		type = "light_radius", 
		level = 44, 
		id = "delve_light_radius_+%", 
		value = 1320, 
	},
	{
		type = "light_radius", 
		level = 45, 
		id = "delve_light_radius_+%", 
		value = 1350, 
	},
	{
		type = "light_radius", 
		level = 46, 
		id = "delve_light_radius_+%", 
		value = 1380, 
	},
	{
		type = "light_radius", 
		level = 47, 
		id = "delve_light_radius_+%", 
		value = 1410, 
	},
	{
		type = "light_radius", 
		level = 48, 
		id = "delve_light_radius_+%", 
		value = 1440, 
	},
	{
		type = "light_radius", 
		level = 49, 
		id = "delve_light_radius_+%", 
		value = 1470, 
	},
	{
		type = "light_radius", 
		level = 50, 
		id = "delve_light_radius_+%", 
		value = 1500, 
	},
	{
		type = "light_radius", 
		level = 51, 
		id = "delve_light_radius_+%", 
		value = 1530, 
	},
	{
		type = "light_radius", 
		level = 52, 
		id = "delve_light_radius_+%", 
		value = 1560, 
	},
	{
		type = "light_radius", 
		level = 53, 
		id = "delve_light_radius_+%", 
		value = 1590, 
	},
	{
		type = "light_radius", 
		level = 54, 
		id = "delve_light_radius_+%", 
		value = 1620, 
	},
	{
		type = "light_radius", 
		level = 55, 
		id = "delve_light_radius_+%", 
		value = 1650, 
	},
	{
		type = "light_radius", 
		level = 56, 
		id = "delve_light_radius_+%", 
		value = 1680, 
	},
	{
		type = "light_radius", 
		level = 57, 
		id = "delve_light_radius_+%", 
		value = 1710, 
	},
	{
		type = "light_radius", 
		level = 58, 
		id = "delve_light_radius_+%", 
		value = 1740, 
	},
	{
		type = "light_radius", 
		level = 59, 
		id = "delve_light_radius_+%", 
		value = 1770, 
	},
	{
		type = "light_radius", 
		level = 60, 
		id = "delve_light_radius_+%", 
		value = 1800, 
	},
	{
		type = "light_radius", 
		level = 61, 
		id = "delve_light_radius_+%", 
		value = 1830, 
	},
	{
		type = "light_radius", 
		level = 62, 
		id = "delve_light_radius_+%", 
		value = 1860, 
	},
	{
		type = "light_radius", 
		level = 63, 
		id = "delve_light_radius_+%", 
		value = 1890, 
	},
	{
		type = "light_radius", 
		level = 64, 
		id = "delve_light_radius_+%", 
		value = 1920, 
	},
	{
		type = "light_radius", 
		level = 65, 
		id = "delve_light_radius_+%", 
		value = 1950, 
	},
	{
		type = "light_radius", 
		level = 66, 
		id = "delve_light_radius_+%", 
		value = 1980, 
	},
	{
		type = "light_radius", 
		level = 67, 
		id = "delve_light_radius_+%", 
		value = 2010, 
	},
	{
		type = "light_radius", 
		level = 68, 
		id = "delve_light_radius_+%", 
		value = 2040, 
	},
	{
		type = "light_radius", 
		level = 69, 
		id = "delve_light_radius_+%", 
		value = 2070, 
	},
	{
		type = "light_radius", 
		level = 70, 
		id = "delve_light_radius_+%", 
		value = 2100, 
	},
	{
		type = "light_radius", 
		level = 71, 
		id = "delve_light_radius_+%", 
		value = 2130, 
	},
	{
		type = "light_radius", 
		level = 72, 
		id = "delve_light_radius_+%", 
		value = 2160, 
	},
	{
		type = "light_radius", 
		level = 73, 
		id = "delve_light_radius_+%", 
		value = 2190, 
	},
	{
		type = "light_radius", 
		level = 74, 
		id = "delve_light_radius_+%", 
		value = 2220, 
	},
	{
		type = "light_radius", 
		level = 75, 
		id = "delve_light_radius_+%", 
		value = 2250, 
	},
	{
		type = "light_radius", 
		level = 76, 
		id = "delve_light_radius_+%", 
		value = 2280, 
	},
	{
		type = "light_radius", 
		level = 77, 
		id = "delve_light_radius_+%", 
		value = 2310, 
	},
	{
		type = "light_radius", 
		level = 78, 
		id = "delve_light_radius_+%", 
		value = 2340, 
	},
	{
		type = "light_radius", 
		level = 79, 
		id = "delve_light_radius_+%", 
		value = 2370, 
	},
	{
		type = "light_radius", 
		level = 80, 
		id = "delve_light_radius_+%", 
		value = 2400, 
	},
	{
		type = "light_radius", 
		level = 81, 
		id = "delve_light_radius_+%", 
		value = 2430, 
	},
	{
		type = "light_radius", 
		level = 82, 
		id = "delve_light_radius_+%", 
		value = 2460, 
	},
	{
		type = "light_radius", 
		level = 83, 
		id = "delve_light_radius_+%", 
		value = 2490, 
	},
	{
		type = "light_radius", 
		level = 84, 
		id = "delve_light_radius_+%", 
		value = 2520, 
	},
	{
		type = "light_radius", 
		level = 85, 
		id = "delve_light_radius_+%", 
		value = 2550, 
	},
	{
		type = "light_radius", 
		level = 86, 
		id = "delve_light_radius_+%", 
		value = 2580, 
	},
	{
		type = "light_radius", 
		level = 87, 
		id = "delve_light_radius_+%", 
		value = 2610, 
	},
	{
		type = "light_radius", 
		level = 88, 
		id = "delve_light_radius_+%", 
		value = 2640, 
	},
	{
		type = "light_radius", 
		level = 89, 
		id = "delve_light_radius_+%", 
		value = 2670, 
	},
	{
		type = "light_radius", 
		level = 90, 
		id = "delve_light_radius_+%", 
		value = 2700, 
	},
	{
		type = "light_radius", 
		level = 91, 
		id = "delve_light_radius_+%", 
		value = 2730, 
	},
	{
		type = "light_radius", 
		level = 92, 
		id = "delve_light_radius_+%", 
		value = 2760, 
	},
	{
		type = "light_radius", 
		level = 93, 
		id = "delve_light_radius_+%", 
		value = 2790, 
	},
	{
		type = "light_radius", 
		level = 94, 
		id = "delve_light_radius_+%", 
		value = 2820, 
	},
	{
		type = "light_radius", 
		level = 95, 
		id = "delve_light_radius_+%", 
		value = 2850, 
	},
	{
		type = "light_radius", 
		level = 96, 
		id = "delve_light_radius_+%", 
		value = 2880, 
	},
	{
		type = "light_radius", 
		level = 97, 
		id = "delve_light_radius_+%", 
		value = 2910, 
	},
	{
		type = "light_radius", 
		level = 98, 
		id = "delve_light_radius_+%", 
		value = 2940, 
	},
	{
		type = "light_radius", 
		level = 99, 
		id = "delve_light_radius_+%", 
		value = 2970, 
	},
	{
		type = "light_radius", 
		level = 100, 
		id = "delve_light_radius_+%", 
		value = 3000, 
	},
	{
		type = "light_radius", 
		level = 101, 
		id = "delve_light_radius_+%", 
		value = 3030, 
	},
	{
		type = "light_radius", 
		level = 102, 
		id = "delve_light_radius_+%", 
		value = 3060, 
	},
	{
		type = "light_radius", 
		level = 103, 
		id = "delve_light_radius_+%", 
		value = 3090, 
	},
	{
		type = "light_radius", 
		level = 104, 
		id = "delve_light_radius_+%", 
		value = 3120, 
	},
	{
		type = "light_radius", 
		level = 105, 
		id = "delve_light_radius_+%", 
		value = 3150, 
	},
	{
		type = "flare_radius", 
		level = 0, 
		id = "delve_flare_radius_+%", 
		value = 0, 
	},
	{
		type = "flare_radius", 
		level = 1, 
		id = "delve_flare_radius_+%", 
		value = 30, 
	},
	{
		type = "flare_radius", 
		level = 2, 
		id = "delve_flare_radius_+%", 
		value = 60, 
	},
	{
		type = "flare_radius", 
		level = 3, 
		id = "delve_flare_radius_+%", 
		value = 90, 
	},
	{
		type = "flare_radius", 
		level = 4, 
		id = "delve_flare_radius_+%", 
		value = 120, 
	},
	{
		type = "flare_radius", 
		level = 5, 
		id = "delve_flare_radius_+%", 
		value = 150, 
	},
	{
		type = "flare_radius", 
		level = 6, 
		id = "delve_flare_radius_+%", 
		value = 180, 
	},
	{
		type = "flare_radius", 
		level = 7, 
		id = "delve_flare_radius_+%", 
		value = 210, 
	},
	{
		type = "flare_radius", 
		level = 8, 
		id = "delve_flare_radius_+%", 
		value = 240, 
	},
	{
		type = "flare_radius", 
		level = 9, 
		id = "delve_flare_radius_+%", 
		value = 270, 
	},
	{
		type = "flare_radius", 
		level = 10, 
		id = "delve_flare_radius_+%", 
		value = 300, 
	},
	{
		type = "flare_radius", 
		level = 11, 
		id = "delve_flare_radius_+%", 
		value = 330, 
	},
	{
		type = "flare_radius", 
		level = 12, 
		id = "delve_flare_radius_+%", 
		value = 360, 
	},
	{
		type = "flare_radius", 
		level = 13, 
		id = "delve_flare_radius_+%", 
		value = 390, 
	},
	{
		type = "flare_radius", 
		level = 14, 
		id = "delve_flare_radius_+%", 
		value = 420, 
	},
	{
		type = "flare_radius", 
		level = 15, 
		id = "delve_flare_radius_+%", 
		value = 450, 
	},
	{
		type = "flare_radius", 
		level = 16, 
		id = "delve_flare_radius_+%", 
		value = 480, 
	},
	{
		type = "flare_radius", 
		level = 17, 
		id = "delve_flare_radius_+%", 
		value = 510, 
	},
	{
		type = "flare_radius", 
		level = 18, 
		id = "delve_flare_radius_+%", 
		value = 540, 
	},
	{
		type = "flare_radius", 
		level = 19, 
		id = "delve_flare_radius_+%", 
		value = 570, 
	},
	{
		type = "flare_radius", 
		level = 20, 
		id = "delve_flare_radius_+%", 
		value = 600, 
	},
	{
		type = "flare_radius", 
		level = 21, 
		id = "delve_flare_radius_+%", 
		value = 630, 
	},
	{
		type = "flare_radius", 
		level = 22, 
		id = "delve_flare_radius_+%", 
		value = 660, 
	},
	{
		type = "flare_radius", 
		level = 23, 
		id = "delve_flare_radius_+%", 
		value = 690, 
	},
	{
		type = "flare_radius", 
		level = 24, 
		id = "delve_flare_radius_+%", 
		value = 720, 
	},
	{
		type = "flare_radius", 
		level = 25, 
		id = "delve_flare_radius_+%", 
		value = 750, 
	},
	{
		type = "flare_radius", 
		level = 26, 
		id = "delve_flare_radius_+%", 
		value = 780, 
	},
	{
		type = "flare_radius", 
		level = 27, 
		id = "delve_flare_radius_+%", 
		value = 810, 
	},
	{
		type = "flare_radius", 
		level = 28, 
		id = "delve_flare_radius_+%", 
		value = 840, 
	},
	{
		type = "flare_radius", 
		level = 29, 
		id = "delve_flare_radius_+%", 
		value = 870, 
	},
	{
		type = "flare_radius", 
		level = 30, 
		id = "delve_flare_radius_+%", 
		value = 900, 
	},
	{
		type = "flare_radius", 
		level = 31, 
		id = "delve_flare_radius_+%", 
		value = 930, 
	},
	{
		type = "flare_radius", 
		level = 32, 
		id = "delve_flare_radius_+%", 
		value = 960, 
	},
	{
		type = "flare_radius", 
		level = 33, 
		id = "delve_flare_radius_+%", 
		value = 990, 
	},
	{
		type = "flare_radius", 
		level = 34, 
		id = "delve_flare_radius_+%", 
		value = 1020, 
	},
	{
		type = "flare_radius", 
		level = 35, 
		id = "delve_flare_radius_+%", 
		value = 1050, 
	},
	{
		type = "flare_radius", 
		level = 36, 
		id = "delve_flare_radius_+%", 
		value = 1080, 
	},
	{
		type = "flare_radius", 
		level = 37, 
		id = "delve_flare_radius_+%", 
		value = 1110, 
	},
	{
		type = "flare_radius", 
		level = 38, 
		id = "delve_flare_radius_+%", 
		value = 1140, 
	},
	{
		type = "flare_radius", 
		level = 39, 
		id = "delve_flare_radius_+%", 
		value = 1170, 
	},
	{
		type = "flare_radius", 
		level = 40, 
		id = "delve_flare_radius_+%", 
		value = 1200, 
	},
	{
		type = "flare_radius", 
		level = 41, 
		id = "delve_flare_radius_+%", 
		value = 1230, 
	},
	{
		type = "flare_radius", 
		level = 42, 
		id = "delve_flare_radius_+%", 
		value = 1260, 
	},
	{
		type = "flare_radius", 
		level = 43, 
		id = "delve_flare_radius_+%", 
		value = 1290, 
	},
	{
		type = "flare_radius", 
		level = 44, 
		id = "delve_flare_radius_+%", 
		value = 1320, 
	},
	{
		type = "flare_radius", 
		level = 45, 
		id = "delve_flare_radius_+%", 
		value = 1350, 
	},
	{
		type = "flare_radius", 
		level = 46, 
		id = "delve_flare_radius_+%", 
		value = 1380, 
	},
	{
		type = "flare_radius", 
		level = 47, 
		id = "delve_flare_radius_+%", 
		value = 1410, 
	},
	{
		type = "flare_radius", 
		level = 48, 
		id = "delve_flare_radius_+%", 
		value = 1440, 
	},
	{
		type = "flare_radius", 
		level = 49, 
		id = "delve_flare_radius_+%", 
		value = 1470, 
	},
	{
		type = "flare_radius", 
		level = 50, 
		id = "delve_flare_radius_+%", 
		value = 1500, 
	},
	{
		type = "flare_radius", 
		level = 51, 
		id = "delve_flare_radius_+%", 
		value = 1530, 
	},
	{
		type = "flare_radius", 
		level = 52, 
		id = "delve_flare_radius_+%", 
		value = 1560, 
	},
	{
		type = "flare_radius", 
		level = 53, 
		id = "delve_flare_radius_+%", 
		value = 1590, 
	},
	{
		type = "flare_radius", 
		level = 54, 
		id = "delve_flare_radius_+%", 
		value = 1620, 
	},
	{
		type = "flare_radius", 
		level = 55, 
		id = "delve_flare_radius_+%", 
		value = 1650, 
	},
	{
		type = "flare_radius", 
		level = 56, 
		id = "delve_flare_radius_+%", 
		value = 1680, 
	},
	{
		type = "flare_radius", 
		level = 57, 
		id = "delve_flare_radius_+%", 
		value = 1710, 
	},
	{
		type = "flare_radius", 
		level = 58, 
		id = "delve_flare_radius_+%", 
		value = 1740, 
	},
	{
		type = "flare_radius", 
		level = 59, 
		id = "delve_flare_radius_+%", 
		value = 1770, 
	},
	{
		type = "flare_radius", 
		level = 60, 
		id = "delve_flare_radius_+%", 
		value = 1800, 
	},
	{
		type = "flare_radius", 
		level = 61, 
		id = "delve_flare_radius_+%", 
		value = 1830, 
	},
	{
		type = "flare_radius", 
		level = 62, 
		id = "delve_flare_radius_+%", 
		value = 1860, 
	},
	{
		type = "flare_radius", 
		level = 63, 
		id = "delve_flare_radius_+%", 
		value = 1890, 
	},
	{
		type = "flare_radius", 
		level = 64, 
		id = "delve_flare_radius_+%", 
		value = 1920, 
	},
	{
		type = "flare_radius", 
		level = 65, 
		id = "delve_flare_radius_+%", 
		value = 1950, 
	},
	{
		type = "flare_radius", 
		level = 66, 
		id = "delve_flare_radius_+%", 
		value = 1980, 
	},
	{
		type = "flare_radius", 
		level = 67, 
		id = "delve_flare_radius_+%", 
		value = 2010, 
	},
	{
		type = "flare_radius", 
		level = 68, 
		id = "delve_flare_radius_+%", 
		value = 2040, 
	},
	{
		type = "flare_radius", 
		level = 69, 
		id = "delve_flare_radius_+%", 
		value = 2070, 
	},
	{
		type = "flare_radius", 
		level = 70, 
		id = "delve_flare_radius_+%", 
		value = 2100, 
	},
	{
		type = "flare_radius", 
		level = 71, 
		id = "delve_flare_radius_+%", 
		value = 2130, 
	},
	{
		type = "flare_radius", 
		level = 72, 
		id = "delve_flare_radius_+%", 
		value = 2160, 
	},
	{
		type = "flare_radius", 
		level = 73, 
		id = "delve_flare_radius_+%", 
		value = 2190, 
	},
	{
		type = "flare_radius", 
		level = 74, 
		id = "delve_flare_radius_+%", 
		value = 2220, 
	},
	{
		type = "flare_radius", 
		level = 75, 
		id = "delve_flare_radius_+%", 
		value = 2250, 
	},
	{
		type = "flare_radius", 
		level = 76, 
		id = "delve_flare_radius_+%", 
		value = 2280, 
	},
	{
		type = "flare_radius", 
		level = 77, 
		id = "delve_flare_radius_+%", 
		value = 2310, 
	},
	{
		type = "flare_radius", 
		level = 78, 
		id = "delve_flare_radius_+%", 
		value = 2340, 
	},
	{
		type = "flare_radius", 
		level = 79, 
		id = "delve_flare_radius_+%", 
		value = 2370, 
	},
	{
		type = "flare_radius", 
		level = 80, 
		id = "delve_flare_radius_+%", 
		value = 2400, 
	},
	{
		type = "flare_radius", 
		level = 81, 
		id = "delve_flare_radius_+%", 
		value = 2430, 
	},
	{
		type = "flare_radius", 
		level = 82, 
		id = "delve_flare_radius_+%", 
		value = 2460, 
	},
	{
		type = "flare_radius", 
		level = 83, 
		id = "delve_flare_radius_+%", 
		value = 2490, 
	},
	{
		type = "flare_radius", 
		level = 84, 
		id = "delve_flare_radius_+%", 
		value = 2520, 
	},
	{
		type = "flare_radius", 
		level = 85, 
		id = "delve_flare_radius_+%", 
		value = 2550, 
	},
	{
		type = "flare_radius", 
		level = 86, 
		id = "delve_flare_radius_+%", 
		value = 2580, 
	},
	{
		type = "flare_radius", 
		level = 87, 
		id = "delve_flare_radius_+%", 
		value = 2610, 
	},
	{
		type = "flare_radius", 
		level = 88, 
		id = "delve_flare_radius_+%", 
		value = 2640, 
	},
	{
		type = "flare_radius", 
		level = 89, 
		id = "delve_flare_radius_+%", 
		value = 2670, 
	},
	{
		type = "flare_radius", 
		level = 90, 
		id = "delve_flare_radius_+%", 
		value = 2700, 
	},
	{
		type = "flare_radius", 
		level = 91, 
		id = "delve_flare_radius_+%", 
		value = 2730, 
	},
	{
		type = "flare_radius", 
		level = 92, 
		id = "delve_flare_radius_+%", 
		value = 2760, 
	},
	{
		type = "flare_radius", 
		level = 93, 
		id = "delve_flare_radius_+%", 
		value = 2790, 
	},
	{
		type = "flare_radius", 
		level = 94, 
		id = "delve_flare_radius_+%", 
		value = 2820, 
	},
	{
		type = "flare_radius", 
		level = 95, 
		id = "delve_flare_radius_+%", 
		value = 2850, 
	},
	{
		type = "flare_radius", 
		level = 96, 
		id = "delve_flare_radius_+%", 
		value = 2880, 
	},
	{
		type = "flare_radius", 
		level = 97, 
		id = "delve_flare_radius_+%", 
		value = 2910, 
	},
	{
		type = "flare_radius", 
		level = 98, 
		id = "delve_flare_radius_+%", 
		value = 2940, 
	},
	{
		type = "flare_radius", 
		level = 99, 
		id = "delve_flare_radius_+%", 
		value = 2970, 
	},
	{
		type = "flare_radius", 
		level = 100, 
		id = "delve_flare_radius_+%", 
		value = 3000, 
	},
	{
		type = "flare_radius", 
		level = 101, 
		id = "delve_flare_radius_+%", 
		value = 3030, 
	},
	{
		type = "flare_radius", 
		level = 102, 
		id = "delve_flare_radius_+%", 
		value = 3060, 
	},
	{
		type = "flare_radius", 
		level = 103, 
		id = "delve_flare_radius_+%", 
		value = 3090, 
	},
	{
		type = "flare_radius", 
		level = 104, 
		id = "delve_flare_radius_+%", 
		value = 3120, 
	},
	{
		type = "flare_radius", 
		level = 105, 
		id = "delve_flare_radius_+%", 
		value = 3150, 
	},
	{
		type = "dynamite_damage", 
		level = 0, 
		id = "delve_dynamite_damage_+%", 
		value = 0, 
	},
	{
		type = "dynamite_damage", 
		level = 1, 
		id = "delve_dynamite_damage_+%", 
		value = 15, 
	},
	{
		type = "dynamite_damage", 
		level = 2, 
		id = "delve_dynamite_damage_+%", 
		value = 40, 
	},
	{
		type = "dynamite_damage", 
		level = 3, 
		id = "delve_dynamite_damage_+%", 
		value = 75, 
	},
	{
		type = "dynamite_damage", 
		level = 4, 
		id = "delve_dynamite_damage_+%", 
		value = 100, 
	},
	{
		type = "dynamite_damage", 
		level = 5, 
		id = "delve_dynamite_damage_+%", 
		value = 125, 
	},
	{
		type = "dynamite_damage", 
		level = 6, 
		id = "delve_dynamite_damage_+%", 
		value = 150, 
	},
	{
		type = "dynamite_damage", 
		level = 7, 
		id = "delve_dynamite_damage_+%", 
		value = 175, 
	},
	{
		type = "dynamite_damage", 
		level = 8, 
		id = "delve_dynamite_damage_+%", 
		value = 200, 
	},
	{
		type = "dynamite_damage", 
		level = 9, 
		id = "delve_dynamite_damage_+%", 
		value = 225, 
	},
	{
		type = "dynamite_damage", 
		level = 10, 
		id = "delve_dynamite_damage_+%", 
		value = 250, 
	},
	{
		type = "darkness_resistance", 
		level = 0, 
		id = "delve_darkness_resistance_%", 
		value = 0, 
	},
	{
		type = "darkness_resistance", 
		level = 1, 
		id = "delve_darkness_resistance_%", 
		value = 30, 
	},
	{
		type = "darkness_resistance", 
		level = 2, 
		id = "delve_darkness_resistance_%", 
		value = 60, 
	},
	{
		type = "darkness_resistance", 
		level = 3, 
		id = "delve_darkness_resistance_%", 
		value = 90, 
	},
	{
		type = "darkness_resistance", 
		level = 4, 
		id = "delve_darkness_resistance_%", 
		value = 120, 
	},
	{
		type = "darkness_resistance", 
		level = 5, 
		id = "delve_darkness_resistance_%", 
		value = 150, 
	},
	{
		type = "darkness_resistance", 
		level = 6, 
		id = "delve_darkness_resistance_%", 
		value = 180, 
	},
	{
		type = "darkness_resistance", 
		level = 7, 
		id = "delve_darkness_resistance_%", 
		value = 210, 
	},
	{
		type = "darkness_resistance", 
		level = 8, 
		id = "delve_darkness_resistance_%", 
		value = 240, 
	},
	{
		type = "darkness_resistance", 
		level = 9, 
		id = "delve_darkness_resistance_%", 
		value = 270, 
	},
	{
		type = "darkness_resistance", 
		level = 10, 
		id = "delve_darkness_resistance_%", 
		value = 300, 
	},
	{
		type = "darkness_resistance", 
		level = 11, 
		id = "delve_darkness_resistance_%", 
		value = 330, 
	},
	{
		type = "darkness_resistance", 
		level = 12, 
		id = "delve_darkness_resistance_%", 
		value = 360, 
	},
	{
		type = "darkness_resistance", 
		level = 13, 
		id = "delve_darkness_resistance_%", 
		value = 390, 
	},
	{
		type = "darkness_resistance", 
		level = 14, 
		id = "delve_darkness_resistance_%", 
		value = 420, 
	},
	{
		type = "darkness_resistance", 
		level = 15, 
		id = "delve_darkness_resistance_%", 
		value = 450, 
	},
	{
		type = "darkness_resistance", 
		level = 16, 
		id = "delve_darkness_resistance_%", 
		value = 480, 
	},
	{
		type = "darkness_resistance", 
		level = 17, 
		id = "delve_darkness_resistance_%", 
		value = 510, 
	},
	{
		type = "darkness_resistance", 
		level = 18, 
		id = "delve_darkness_resistance_%", 
		value = 540, 
	},
	{
		type = "darkness_resistance", 
		level = 19, 
		id = "delve_darkness_resistance_%", 
		value = 570, 
	},
	{
		type = "darkness_resistance", 
		level = 20, 
		id = "delve_darkness_resistance_%", 
		value = 600, 
	},
	{
		type = "darkness_resistance", 
		level = 21, 
		id = "delve_darkness_resistance_%", 
		value = 630, 
	},
	{
		type = "darkness_resistance", 
		level = 22, 
		id = "delve_darkness_resistance_%", 
		value = 660, 
	},
	{
		type = "darkness_resistance", 
		level = 23, 
		id = "delve_darkness_resistance_%", 
		value = 690, 
	},
	{
		type = "darkness_resistance", 
		level = 24, 
		id = "delve_darkness_resistance_%", 
		value = 720, 
	},
	{
		type = "darkness_resistance", 
		level = 25, 
		id = "delve_darkness_resistance_%", 
		value = 750, 
	},
	{
		type = "darkness_resistance", 
		level = 26, 
		id = "delve_darkness_resistance_%", 
		value = 780, 
	},
	{
		type = "darkness_resistance", 
		level = 27, 
		id = "delve_darkness_resistance_%", 
		value = 810, 
	},
	{
		type = "darkness_resistance", 
		level = 28, 
		id = "delve_darkness_resistance_%", 
		value = 840, 
	},
	{
		type = "darkness_resistance", 
		level = 29, 
		id = "delve_darkness_resistance_%", 
		value = 870, 
	},
	{
		type = "darkness_resistance", 
		level = 30, 
		id = "delve_darkness_resistance_%", 
		value = 900, 
	},
	{
		type = "darkness_resistance", 
		level = 31, 
		id = "delve_darkness_resistance_%", 
		value = 930, 
	},
	{
		type = "darkness_resistance", 
		level = 32, 
		id = "delve_darkness_resistance_%", 
		value = 960, 
	},
	{
		type = "darkness_resistance", 
		level = 33, 
		id = "delve_darkness_resistance_%", 
		value = 990, 
	},
	{
		type = "darkness_resistance", 
		level = 34, 
		id = "delve_darkness_resistance_%", 
		value = 1020, 
	},
	{
		type = "darkness_resistance", 
		level = 35, 
		id = "delve_darkness_resistance_%", 
		value = 1050, 
	},
	{
		type = "darkness_resistance", 
		level = 36, 
		id = "delve_darkness_resistance_%", 
		value = 1080, 
	},
	{
		type = "darkness_resistance", 
		level = 37, 
		id = "delve_darkness_resistance_%", 
		value = 1110, 
	},
	{
		type = "darkness_resistance", 
		level = 38, 
		id = "delve_darkness_resistance_%", 
		value = 1140, 
	},
	{
		type = "darkness_resistance", 
		level = 39, 
		id = "delve_darkness_resistance_%", 
		value = 1170, 
	},
	{
		type = "darkness_resistance", 
		level = 40, 
		id = "delve_darkness_resistance_%", 
		value = 1200, 
	},
	{
		type = "darkness_resistance", 
		level = 41, 
		id = "delve_darkness_resistance_%", 
		value = 1230, 
	},
	{
		type = "darkness_resistance", 
		level = 42, 
		id = "delve_darkness_resistance_%", 
		value = 1260, 
	},
	{
		type = "darkness_resistance", 
		level = 43, 
		id = "delve_darkness_resistance_%", 
		value = 1290, 
	},
	{
		type = "darkness_resistance", 
		level = 44, 
		id = "delve_darkness_resistance_%", 
		value = 1320, 
	},
	{
		type = "darkness_resistance", 
		level = 45, 
		id = "delve_darkness_resistance_%", 
		value = 1350, 
	},
	{
		type = "darkness_resistance", 
		level = 46, 
		id = "delve_darkness_resistance_%", 
		value = 1380, 
	},
	{
		type = "darkness_resistance", 
		level = 47, 
		id = "delve_darkness_resistance_%", 
		value = 1410, 
	},
	{
		type = "darkness_resistance", 
		level = 48, 
		id = "delve_darkness_resistance_%", 
		value = 1440, 
	},
	{
		type = "darkness_resistance", 
		level = 49, 
		id = "delve_darkness_resistance_%", 
		value = 1470, 
	},
	{
		type = "darkness_resistance", 
		level = 50, 
		id = "delve_darkness_resistance_%", 
		value = 1500, 
	},
	{
		type = "darkness_resistance", 
		level = 51, 
		id = "delve_darkness_resistance_%", 
		value = 1530, 
	},
	{
		type = "darkness_resistance", 
		level = 52, 
		id = "delve_darkness_resistance_%", 
		value = 1560, 
	},
	{
		type = "darkness_resistance", 
		level = 53, 
		id = "delve_darkness_resistance_%", 
		value = 1590, 
	},
	{
		type = "darkness_resistance", 
		level = 54, 
		id = "delve_darkness_resistance_%", 
		value = 1620, 
	},
	{
		type = "darkness_resistance", 
		level = 55, 
		id = "delve_darkness_resistance_%", 
		value = 1650, 
	},
	{
		type = "darkness_resistance", 
		level = 56, 
		id = "delve_darkness_resistance_%", 
		value = 1680, 
	},
	{
		type = "darkness_resistance", 
		level = 57, 
		id = "delve_darkness_resistance_%", 
		value = 1710, 
	},
	{
		type = "darkness_resistance", 
		level = 58, 
		id = "delve_darkness_resistance_%", 
		value = 1740, 
	},
	{
		type = "darkness_resistance", 
		level = 59, 
		id = "delve_darkness_resistance_%", 
		value = 1770, 
	},
	{
		type = "darkness_resistance", 
		level = 60, 
		id = "delve_darkness_resistance_%", 
		value = 1800, 
	},
	{
		type = "darkness_resistance", 
		level = 61, 
		id = "delve_darkness_resistance_%", 
		value = 1830, 
	},
	{
		type = "darkness_resistance", 
		level = 62, 
		id = "delve_darkness_resistance_%", 
		value = 1860, 
	},
	{
		type = "darkness_resistance", 
		level = 63, 
		id = "delve_darkness_resistance_%", 
		value = 1890, 
	},
	{
		type = "darkness_resistance", 
		level = 64, 
		id = "delve_darkness_resistance_%", 
		value = 1920, 
	},
	{
		type = "darkness_resistance", 
		level = 65, 
		id = "delve_darkness_resistance_%", 
		value = 1950, 
	},
	{
		type = "darkness_resistance", 
		level = 66, 
		id = "delve_darkness_resistance_%", 
		value = 1980, 
	},
	{
		type = "darkness_resistance", 
		level = 67, 
		id = "delve_darkness_resistance_%", 
		value = 2010, 
	},
	{
		type = "darkness_resistance", 
		level = 68, 
		id = "delve_darkness_resistance_%", 
		value = 2040, 
	},
	{
		type = "darkness_resistance", 
		level = 69, 
		id = "delve_darkness_resistance_%", 
		value = 2070, 
	},
	{
		type = "darkness_resistance", 
		level = 70, 
		id = "delve_darkness_resistance_%", 
		value = 2100, 
	},
	{
		type = "darkness_resistance", 
		level = 71, 
		id = "delve_darkness_resistance_%", 
		value = 2130, 
	},
	{
		type = "darkness_resistance", 
		level = 72, 
		id = "delve_darkness_resistance_%", 
		value = 2160, 
	},
	{
		type = "darkness_resistance", 
		level = 73, 
		id = "delve_darkness_resistance_%", 
		value = 2190, 
	},
	{
		type = "darkness_resistance", 
		level = 74, 
		id = "delve_darkness_resistance_%", 
		value = 2220, 
	},
	{
		type = "darkness_resistance", 
		level = 75, 
		id = "delve_darkness_resistance_%", 
		value = 2250, 
	},
	{
		type = "darkness_resistance", 
		level = 76, 
		id = "delve_darkness_resistance_%", 
		value = 2280, 
	},
	{
		type = "darkness_resistance", 
		level = 77, 
		id = "delve_darkness_resistance_%", 
		value = 2310, 
	},
	{
		type = "darkness_resistance", 
		level = 78, 
		id = "delve_darkness_resistance_%", 
		value = 2340, 
	},
	{
		type = "darkness_resistance", 
		level = 79, 
		id = "delve_darkness_resistance_%", 
		value = 2370, 
	},
	{
		type = "darkness_resistance", 
		level = 80, 
		id = "delve_darkness_resistance_%", 
		value = 2400, 
	},
	{
		type = "darkness_resistance", 
		level = 81, 
		id = "delve_darkness_resistance_%", 
		value = 2430, 
	},
	{
		type = "darkness_resistance", 
		level = 82, 
		id = "delve_darkness_resistance_%", 
		value = 2460, 
	},
	{
		type = "darkness_resistance", 
		level = 83, 
		id = "delve_darkness_resistance_%", 
		value = 2490, 
	},
	{
		type = "darkness_resistance", 
		level = 84, 
		id = "delve_darkness_resistance_%", 
		value = 2520, 
	},
	{
		type = "darkness_resistance", 
		level = 85, 
		id = "delve_darkness_resistance_%", 
		value = 2550, 
	},
	{
		type = "darkness_resistance", 
		level = 86, 
		id = "delve_darkness_resistance_%", 
		value = 2580, 
	},
	{
		type = "darkness_resistance", 
		level = 87, 
		id = "delve_darkness_resistance_%", 
		value = 2610, 
	},
	{
		type = "darkness_resistance", 
		level = 88, 
		id = "delve_darkness_resistance_%", 
		value = 2640, 
	},
	{
		type = "darkness_resistance", 
		level = 89, 
		id = "delve_darkness_resistance_%", 
		value = 2670, 
	},
	{
		type = "darkness_resistance", 
		level = 90, 
		id = "delve_darkness_resistance_%", 
		value = 2700, 
	},
	{
		type = "darkness_resistance", 
		level = 91, 
		id = "delve_darkness_resistance_%", 
		value = 2730, 
	},
	{
		type = "darkness_resistance", 
		level = 92, 
		id = "delve_darkness_resistance_%", 
		value = 2760, 
	},
	{
		type = "darkness_resistance", 
		level = 93, 
		id = "delve_darkness_resistance_%", 
		value = 2790, 
	},
	{
		type = "darkness_resistance", 
		level = 94, 
		id = "delve_darkness_resistance_%", 
		value = 2820, 
	},
	{
		type = "darkness_resistance", 
		level = 95, 
		id = "delve_darkness_resistance_%", 
		value = 2850, 
	},
	{
		type = "darkness_resistance", 
		level = 96, 
		id = "delve_darkness_resistance_%", 
		value = 2880, 
	},
	{
		type = "darkness_resistance", 
		level = 97, 
		id = "delve_darkness_resistance_%", 
		value = 2910, 
	},
	{
		type = "darkness_resistance", 
		level = 98, 
		id = "delve_darkness_resistance_%", 
		value = 2940, 
	},
	{
		type = "darkness_resistance", 
		level = 99, 
		id = "delve_darkness_resistance_%", 
		value = 2970, 
	},
	{
		type = "darkness_resistance", 
		level = 100, 
		id = "delve_darkness_resistance_%", 
		value = 3000, 
	},
	{
		type = "darkness_resistance", 
		level = 101, 
		id = "delve_darkness_resistance_%", 
		value = 3030, 
	},
	{
		type = "darkness_resistance", 
		level = 102, 
		id = "delve_darkness_resistance_%", 
		value = 3060, 
	},
	{
		type = "darkness_resistance", 
		level = 103, 
		id = "delve_darkness_resistance_%", 
		value = 3090, 
	},
	{
		type = "darkness_resistance", 
		level = 104, 
		id = "delve_darkness_resistance_%", 
		value = 3120, 
	},
	{
		type = "darkness_resistance", 
		level = 105, 
		id = "delve_darkness_resistance_%", 
		value = 3150, 
	},
	{
		type = "dynamite_radius", 
		level = 0, 
		id = "delve_dynamite_radius_+%", 
		value = 0, 
	},
	{
		type = "dynamite_radius", 
		level = 1, 
		id = "delve_dynamite_radius_+%", 
		value = 25, 
	},
	{
		type = "dynamite_radius", 
		level = 2, 
		id = "delve_dynamite_radius_+%", 
		value = 50, 
	},
	{
		type = "dynamite_radius", 
		level = 3, 
		id = "delve_dynamite_radius_+%", 
		value = 75, 
	},
	{
		type = "dynamite_radius", 
		level = 4, 
		id = "delve_dynamite_radius_+%", 
		value = 100, 
	},
	{
		type = "dynamite_radius", 
		level = 5, 
		id = "delve_dynamite_radius_+%", 
		value = 125, 
	},
	{
		type = "flare_duration", 
		level = 0, 
		id = "delve_flare_duration_ms_+", 
		value = 14000, 
	},
	{
		type = "flare_duration", 
		level = 1, 
		id = "delve_flare_duration_ms_+", 
		value = 15000, 
	},
	{
		type = "flare_duration", 
		level = 2, 
		id = "delve_flare_duration_ms_+", 
		value = 16000, 
	},
	{
		type = "flare_duration", 
		level = 3, 
		id = "delve_flare_duration_ms_+", 
		value = 17000, 
	},
	{
		type = "flare_duration", 
		level = 4, 
		id = "delve_flare_duration_ms_+", 
		value = 18000, 
	},
	{
		type = "flare_duration", 
		level = 5, 
		id = "delve_flare_duration_ms_+", 
		value = 19000, 
	},
	{
		type = "flare_duration", 
		level = 6, 
		id = "delve_flare_duration_ms_+", 
		value = 20000, 
	},
	{
		type = "flare_duration", 
		level = 7, 
		id = "delve_flare_duration_ms_+", 
		value = 21000, 
	},
	{
		type = "flare_duration", 
		level = 8, 
		id = "delve_flare_duration_ms_+", 
		value = 22000, 
	},
	{
		type = "flare_duration", 
		level = 9, 
		id = "delve_flare_duration_ms_+", 
		value = 23000, 
	},
	{
		type = "flare_duration", 
		level = 10, 
		id = "delve_flare_duration_ms_+", 
		value = 24000, 
	}}
return data