local data = {	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingFire", 
		type = "override", 
		ordinal = 0, 
		tag = "cold", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingFire", 
		type = "added", 
		ordinal = 0, 
		tag = "fire", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingCold", 
		type = "override", 
		ordinal = 0, 
		tag = "fire", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingCold", 
		type = "added", 
		ordinal = 0, 
		tag = "cold", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingLightning", 
		type = "override", 
		ordinal = 0, 
		tag = "physical", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingLightning", 
		type = "added", 
		ordinal = 0, 
		tag = "lightning", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingPhysical", 
		type = "override", 
		ordinal = 0, 
		tag = "chaos", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingPhysical", 
		type = "added", 
		ordinal = 0, 
		tag = "physical", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingChaos", 
		type = "override", 
		ordinal = 0, 
		tag = "lightning", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingChaos", 
		type = "added", 
		ordinal = 0, 
		tag = "chaos", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingLife", 
		type = "override", 
		ordinal = 0, 
		tag = "defences", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingLife", 
		type = "added", 
		ordinal = 0, 
		tag = "life", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingDefences", 
		type = "override", 
		ordinal = 0, 
		tag = "life", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingDefences", 
		type = "added", 
		ordinal = 0, 
		tag = "defences", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingBleedPoison", 
		type = "override", 
		ordinal = 0, 
		tag = "elemental", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingBleedPoison", 
		type = "added", 
		ordinal = 0, 
		tag = "bleed", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingBleedPoison", 
		type = "added", 
		ordinal = 1, 
		tag = "poison", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingElemental", 
		type = "override", 
		ordinal = 0, 
		tag = "bleed", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingElemental", 
		type = "override", 
		ordinal = 1, 
		tag = "poison", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingElemental", 
		type = "added", 
		ordinal = 0, 
		tag = "elemental", 
		weight = 600, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingCasterMods", 
		type = "override", 
		ordinal = 0, 
		tag = "attack", 
		weight = 15, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingCasterMods", 
		type = "added", 
		ordinal = 0, 
		tag = "caster", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingAttackMods", 
		type = "override", 
		ordinal = 0, 
		tag = "caster", 
		weight = 15, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingAttackMods", 
		type = "added", 
		ordinal = 0, 
		tag = "attack", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingMana", 
		type = "override", 
		ordinal = 0, 
		tag = "speed", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingMana", 
		type = "added", 
		ordinal = 0, 
		tag = "mana", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingSpeed", 
		type = "override", 
		ordinal = 0, 
		tag = "mana", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingSpeed", 
		type = "added", 
		ordinal = 0, 
		tag = "speed", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingMinionsAuras", 
		type = "added", 
		ordinal = 0, 
		tag = "minion", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingMinionsAuras", 
		type = "added", 
		ordinal = 1, 
		tag = "aura", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingMinionsAuras", 
		type = "added", 
		ordinal = 2, 
		tag = "curse", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingEnchant", 
		type = "override", 
		ordinal = 0, 
		tag = "attribute", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingEnchant", 
		type = "added", 
		ordinal = 0, 
		tag = "critical", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingSockets", 
		type = "override", 
		ordinal = 0, 
		tag = "critical", 
		weight = 0, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingSockets", 
		type = "added", 
		ordinal = 0, 
		tag = "attribute", 
		weight = 1000, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingGemLevel", 
		type = "added", 
		ordinal = 0, 
		tag = "gem", 
		weight = 1000, 
	}}
return data