local data = {	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingFire", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingCold", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingLightning", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingPhysical", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingChaos", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingLife", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingDefences", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingBleedPoison", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingElemental", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingCasterMods", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingAttackMods", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingMana", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingSpeed", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingMinionsAuras", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingQuality", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {"weapon",
"body_armour",
"gloves",
"boots",
"helmet",
"shield",
"map"}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = true, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingEnchant", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingSockets", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingGemLevel", 
		added_modifier_ids = {"DelveStrengthGemLevel1",
"DelveDexterityGemLevel1",
"DelveIntelligenceGemLevel1"}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingVaal", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {"heist_contract",
"heist_blueprint",
"heist_equipment"}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingAbyss", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {"DelveAbyssJewelSocket1"}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {"weapon",
"helmet",
"boots",
"gloves",
"body_armour"}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingMirror", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = true, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingCorruptEssence", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {"weapon",
"body_armour",
"gloves",
"boots",
"helmet",
"shield",
"amulet",
"belt",
"ring",
"quiver"}, 
		corrupted_essence_chance = 100, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingRandom", 
		added_modifier_ids = {"DelveStrengthGemLevel1",
"DelveDexterityGemLevel1",
"DelveIntelligenceGemLevel1",
"DelveWeaponVaalSoulCost1h1_",
"DelveWeaponVaalSoulCost2h1",
"DelveArmourVaalSoulsOnKill1_",
"DelveGlovesVaalSkillCriticalChance1",
"DelveAmuletVaalSkillDuration1",
"DelveJewelryVaalSkillDamage1",
"DelveJewelVaalSoulsOnKill1",
"DelveAbyssJewelSocket1"}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 10, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingLuckyModRolls", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = true, 
	},
	{
		base_item_id = "Metadata/Items/Currency/CurrencyDelveCraftingSellPrice", 
		added_modifier_ids = {}, 
		forced_modifier_ids = {}, 
		sell_price_modifier_ids = {"DoubleModSellPrice1",
"DoubleModSellPrice2",
"DoubleModSellPrice3_",
"DoubleModSellPrice4",
"DoubleModSellPrice5_",
"DoubleModSellPrice6",
"DoubleModSellPrice7",
"DoubleModSellPrice8",
"DoubleModSellPrice9"}, 
		forbidden_tags = {}, 
		allowed_tags = {}, 
		corrupted_essence_chance = 0, 
		can_mirror = false, 
		can_enchant = false, 
		can_quality = false, 
		can_roll_white_sockets = false, 
		is_lucky = false, 
	}}
return data