local data = {	{
		id = "ReforgeFire", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|orange|Fire}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Fire modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 50, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"fire",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeCold", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|blue|Cold}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Cold modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 50, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"cold",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeLightning", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|yellow|Lightning}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Lightning modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 50, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"lightning",
"ON",
"rare"}, 
	},
	{
		id = "ReforgePhysical", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|tan|Physical}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Physical modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 50, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"physical",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeLife", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|red|Life}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Life modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 75, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"life",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeDefences", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|white|Defence}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Defence modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 75, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"defences",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeChaos", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|purple|Chaos}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Chaos modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 100, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"chaos",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeAttack", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including an {{c|white|Attack}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including an Attack modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 75, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"attack",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeSpell", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|purple|Caster}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Caster modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 75, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"caster",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeSpeed", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|green|Speed}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Speed modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 150, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"speed",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeCritical", 
		text = "{{c|white|Reforge}} a Rare item with random modifiers, including a {{c|blue|Critical}} modifier", 
		tier = 0, 
		effect = "Reforge a Rare item with random modifiers, including a Critical modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 150, 
		cost_sacred = 0, 
		command = "reroll_with_mod", 
		parameters = {"critical",
"ON",
"rare"}, 
	},
	{
		id = "ReforgeMoreLikely", 
		text = "{{c|white|Reforge}} a {{c|white|Rare}} item, being {{c|white|more likely}} to receive the same modifier types", 
		tier = 0, 
		effect = "Reforge a Rare item, being more likely to receive the same modifier types", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 200, 
		cost_sacred = 0, 
		command = "reroll_with_current_tags_affinity_multiplier", 
		parameters = {"900"}, 
	},
	{
		id = "ReforgeLessLikely", 
		text = "{{c|white|Reforge}} a {{c|white|Rare}} item, being {{c|white|less likely}} to receive the same modifier types", 
		tier = 0, 
		effect = "Reforge a Rare item, being less likely to receive the same modifier types", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 200, 
		cost_sacred = 0, 
		command = "reroll_with_current_tags_affinity_multiplier", 
		parameters = {"-90"}, 
	},
	{
		id = "RerollCorruptedMap", 
		text = "{{c|white|Sacrifice}} a Rare {{c|white|Corrupted Map}}. Create a new Corrupted Map of the same tier and rarity.", 
		tier = 0, 
		effect = "Sacrifice a Rare Corrupted Map. Create a new Corrupted Map of the same tier and rarity.", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 200, 
		cost_sacred = 0, 
		command = "sacrifice_corrupted_map_for_new_corrupted_map", 
	},
	{
		id = "RerollFossils", 
		text = "{{c|white|Change}} a stack of {{c|white|Fossils}} into a different type of Fossil. The new Fossil type may have a smaller stack size. Cost is proportional to stack size.", 
		tier = 0, 
		effect = "Change a stack of Fossils into a different type of Fossil. The new Fossil type may have a smaller stack size. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 30, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"delvefossils"}, 
	},
	{
		id = "RerollOils", 
		text = "{{c|white|Change}} a stack of {{c|white|Oils}} into a different colour of Oil. Cost is proportional to stack size.", 
		tier = 0, 
		effect = "Change a stack of Oils into a different colour of Oil. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 30, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"mushrune"}, 
	},
	{
		id = "RerollCatalysts", 
		text = "{{c|white|Change}} a stack of {{c|white|Catalysts}} into a different type of Catalyst. Cost is proportional to stack size.", 
		tier = 0, 
		effect = "Change a stack of Catalysts into a different type of Catalyst. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 30, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"metamorphcatalystsspecial"}, 
	},
	{
		id = "RerollEssences", 
		text = "{{c|white|Change}} a stack of {{c|white|Essences}} into a different type of the same tier. Cost is proportional to stack size.", 
		tier = 0, 
		effect = "Change a stack of Essences into a different type of the same tier. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 30, 
		cost_sacred = 0, 
		command = "exchange_essences_for_other_essence_of_same_tier", 
	},
	{
		id = "RerollTimelessSplinters", 
		text = "{{c|white|Change}} a stack of {{c|white|Timeless Splinters}} or a {{c|white|Timeless Emblem}} into Splinters or an Emblem of another type. Cost is proportional to stack size.", 
		tier = 0, 
		effect = "Change a stack of Timeless Splinters or a Timeless Emblem into Splinters or an Emblem of another type. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 4, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"HarvestTimelessSplinterExchange",
"HarvestTimelessEmblemExchange"}, 
	},
	{
		id = "RerollBreachSplinters", 
		text = "{{c|white|Change}} a stack of {{c|white|Breach Splinters}} or a normal or Flawless {{c|white|Breachstone}} into Splinters or a Breachstone of another type. Cost is proportional to stack size.", 
		tier = 0, 
		effect = "Change a stack of Breach Splinters or a normal or Flawless Breachstone into Splinters or a Breachstone of another type. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 4, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"HarvestBreachSplinterExchange",
"HarvestBreachStoneExchange",
"HarvestBreachStoneExchange5"}, 
	},
	{
		id = "RerollScarabs", 
		text = "{{c|white|Change}} a stack of {{c|white|Scarabs}} to a different type of the same rarity. Cost is proportional to stack size.", 
		tier = 0, 
		effect = "Change a stack of Scarabs to a different type of the same rarity. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 30, 
		cost_sacred = 0, 
		command = "change_scarab_into_other_of_same_tier", 
	},
	{
		id = "RerollDeliriumOrbs", 
		text = "{{c|white|Change}} a stack of {{c|white|Delirium Orbs}} into a different type of Delirium Orb. Cost is proportional to stack size.", 
		tier = 0, 
		effect = "Change a stack of Delirium Orbs into a different type of Delirium Orb. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 30, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"afflictionorbs"}, 
	},
	{
		id = "RerollDivinationCards", 
		text = "{{c|white|Change}} a {{c|white|Divination Card}} into another random Divination Card", 
		tier = 0, 
		effect = "Change a Divination Card into another random Divination Card", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 75, 
		cost_sacred = 0, 
		command = "reroll_into_new_div_card", 
	},
	{
		id = "ChangeColdToFireResist", 
		text = "{{c|white|Change}} a modifier that grants {{c|blue|Cold}} Resistance into a similar-tier modifier that grants {{c|orange|Fire}} Resistance", 
		tier = 1, 
		effect = "Change a modifier that grants Cold Resistance into a similar-tier modifier that grants Fire Resistance", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "convert_mod", 
		parameters = {"ColdResistance",
"ColdResistanceAilments",
"ColdResistanceForJewel",
"ColdResistanceLeech",
"MaximumColdResist",
"ColdResistancePhysTakenAsCold",
"ColdResistancePrefix",
"AfflictionJewelSmallPassivesGrantColdRes",
"CONVERT",
"cold",
"fire"}, 
	},
	{
		id = "ChangeLightningToFireResist", 
		text = "{{c|white|Change}} a modifier that grants {{c|yellow|Lightning}} Resistance into a similar-tier modifier that grants {{c|orange|Fire}} Resistance", 
		tier = 1, 
		effect = "Change a modifier that grants Lightning Resistance into a similar-tier modifier that grants Fire Resistance", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "convert_mod", 
		parameters = {"LightningResistance",
"LightningResistanceAilments",
"LightningResistanceForJewel",
"LightningResistanceLeech",
"MaximumLightningResistance",
"LightningResistancePhysTakenAsLightning",
"LightningResistancePrefix",
"AfflictionJewelSmallPassivesGrantLightningRes",
"CONVERT",
"lightning",
"fire"}, 
	},
	{
		id = "ChangeFireToColdResist", 
		text = "{{c|white|Change}} a modifier that grants {{c|orange|Fire}} Resistance into a similar-tier modifier that grants {{c|blue|Cold}} Resistance", 
		tier = 1, 
		effect = "Change a modifier that grants Fire Resistance into a similar-tier modifier that grants Cold Resistance", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "convert_mod", 
		parameters = {"FireResistance",
"FireResistanceAilments",
"FireResistanceForJewel",
"FireResistanceLeech",
"MaximumFireResist",
"FireResistancePhysTakenAsFire",
"FireResistancePrefix",
"AfflictionJewelSmallPassivesGrantFireRes",
"CONVERT",
"fire",
"cold"}, 
	},
	{
		id = "ChangeLightningToColdResist", 
		text = "{{c|white|Change}} a modifier that grants {{c|yellow|Lightning}} Resistance into a similar-tier modifier that grants {{c|blue|Cold}} Resistance", 
		tier = 1, 
		effect = "Change a modifier that grants Lightning Resistance into a similar-tier modifier that grants Cold Resistance", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "convert_mod", 
		parameters = {"LightningResistance",
"LightningResistanceAilments",
"LightningResistanceForJewel",
"LightningResistanceLeech",
"MaximumLightningResistance",
"LightningResistancePhysTakenAsLightning",
"LightningResistancePrefix",
"AfflictionJewelSmallPassivesGrantLightningRes",
"CONVERT",
"lightning",
"cold"}, 
	},
	{
		id = "ChangeFireToLightningResist", 
		text = "{{c|white|Change}} a modifier that grants {{c|orange|Fire}} Resistance into a similar-tier modifier that grants {{c|yellow|Lightning}} Resistance", 
		tier = 1, 
		effect = "Change a modifier that grants Fire Resistance into a similar-tier modifier that grants Lightning Resistance", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "convert_mod", 
		parameters = {"FireResistance",
"FireResistanceAilments",
"FireResistanceForJewel",
"FireResistanceLeech",
"MaximumFireResist",
"FireResistancePhysTakenAsFire",
"FireResistancePrefix",
"AfflictionJewelSmallPassivesGrantFireRes",
"CONVERT",
"fire",
"lightning"}, 
	},
	{
		id = "ChangeColdToLightningResist", 
		text = "{{c|white|Change}} a modifier that grants {{c|blue|Cold}} Resistance into a similar-tier modifier that grants {{c|yellow|Lightning}} Resistance", 
		tier = 1, 
		effect = "Change a modifier that grants Cold Resistance into a similar-tier modifier that grants Lightning Resistance", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "convert_mod", 
		parameters = {"ColdResistance",
"ColdResistanceAilments",
"ColdResistanceForJewel",
"ColdResistanceLeech",
"MaximumColdResist",
"ColdResistancePhysTakenAsCold",
"ColdResistancePrefix",
"AfflictionJewelSmallPassivesGrantColdRes",
"CONVERT",
"cold",
"lightning"}, 
	},
	{
		id = "FlaskDurationEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Flask}} with a modifier that grants {{c|white|increased Duration}}. The magnitude of this effect decreases with each use", 
		tier = 2, 
		effect = "Enchant a Flask with a modifier that grants increased Duration. The magnitude of this effect decreases with each use", 
		is_enchant = true, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 800, 
		cost_sacred = 0, 
		command = "add_enchant_to_flask", 
		parameters = {"HarvestFlaskEnchantmentDurationLoweredOnUse1_"}, 
	},
	{
		id = "FlaskChargeEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Flask}} with a modifier that grants {{c|white|increased Maximum Charges}}. The magnitude of this effect decreases with each use", 
		tier = 2, 
		effect = "Enchant a Flask with a modifier that grants increased Maximum Charges. The magnitude of this effect decreases with each use", 
		is_enchant = true, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 800, 
		cost_sacred = 0, 
		command = "add_enchant_to_flask", 
		parameters = {"HarvestFlaskEnchantmentMaximumChargesLoweredOnUse3_"}, 
	},
	{
		id = "FlaskEffectEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Flask}} with a modifier that grants {{c|white|increased Effect}}. The magnitude of this effect decreases with each use", 
		tier = 2, 
		effect = "Enchant a Flask with a modifier that grants increased Effect. The magnitude of this effect decreases with each use", 
		is_enchant = true, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 800, 
		cost_sacred = 0, 
		command = "add_enchant_to_flask", 
		parameters = {"HarvestFlaskEnchantmentEffectLoweredOnUse2"}, 
	},
	{
		id = "FlaskReducedEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Flask}} with a modifier that grants {{c|white|reduced Charges used}}. The magnitude of this effect decreases with each use", 
		tier = 2, 
		effect = "Enchant a Flask with a modifier that grants reduced Charges used. The magnitude of this effect decreases with each use", 
		is_enchant = true, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 800, 
		cost_sacred = 0, 
		command = "add_enchant_to_flask", 
		parameters = {"HarvestFlaskEnchantmentChargesUsedLoweredOnUse4"}, 
	},
	{
		id = "RerollShaperFragment", 
		text = "{{c|white|Change}} a stack of {{c|white|Shaper Fragments}} into other random Shaper Fragments. Cost is proportional to stack size.", 
		tier = 1, 
		effect = "Change a Shaper Fragment into another random Shaper Fragment. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"HarvestShaperFragmentExchange"}, 
	},
	{
		id = "RerollElderFragment", 
		text = "{{c|white|Change}} a stack of {{c|white|Elder Fragments}} into other random Elder Fragments. Cost is proportional to stack size.", 
		tier = 1, 
		effect = "Change an Elder Fragment into another random Elder Fragment. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"HarvestElderFragmentExchange"}, 
	},
	{
		id = "RerollConquerorFragment", 
		text = "{{c|white|Change}} a stack of {{c|white|Conqueror Fragments}} into other random Conqueror Fragments. Cost is proportional to stack size.", 
		tier = 1, 
		effect = "Change a Conqueror Fragment into another random Conqueror Fragment. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"HarvestConquerorFragmentExchange"}, 
	},
	{
		id = "RerollAtziriFragment", 
		text = "{{c|white|Change}} a stack of {{c|white|Sacrifice}} or {{c|white|Mortal Fragments}} into other random Fragments of that type. Cost is proportional to stack size.", 
		tier = 1, 
		effect = "Change a Sacrifice or Mortal Fragment into another random Fragment of that type. Cost is proportional to stack size.", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 500, 
		cost_sacred = 0, 
		command = "exchange_item_in_set_for_other_item_in_set", 
		parameters = {"HarvestSacrificeFragmentExchange",
"HarvestMortalSacrificeFragmentExchange"}, 
	},
	{
		id = "DivinationCardGamble", 
		text = "{{c|white|Sacrifice}} up to half a stack of {{c|white|Divination Cards}} to receive between 0 and twice that amount of the same Card", 
		tier = 1, 
		effect = "Sacrifice up to half a stack of Divination Cards to receive between 0 and twice that amount of the same Card", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 1500, 
		cost_sacred = 0, 
		command = "reroll_num_div_cards", 
	},
	{
		id = "MapNoSextantEnchant", 
		text = "{{c|white|Enchant}} a non-Unique {{c|white|Map}} with {{c|white|Map has 50% chance to not consume Sextant Uses}}", 
		tier = 2, 
		effect = "Enchant a non-Unique Map with Map has 50% chance to not consume Sextant Uses", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 2500, 
		cost_sacred = 0, 
		command = "add_mod_to_map", 
		parameters = {"sextant"}, 
	},
	{
		id = "GemExperienceLens", 
		text = "{{c|white|Sacrifice}} a {{c|white|Corrupted Gem}} to gain 50% of the gem's total experience stored as a {{c|white|Facetor's Lens}}", 
		tier = 2, 
		effect = "Sacrifice a Corrupted Gem to gain 50% of the gem's total experience stored as a Facetor's Lens", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 4000, 
		cost_sacred = 0, 
		command = "sacrifice_gem_for_currency", 
		parameters = {"experience",
"50"}, 
	},
	{
		id = "RerollInfluenceType", 
		text = "{{c|white|Randomise}} the {{c|white|Influence}} types on an Influenced Normal, Magic or Rare {{c|white|Item}}, as well as {{c|white|reforging}} the item with new random modifiers", 
		tier = 2, 
		effect = "Randomise the Influence types on an Influenced Normal, Magic or Rare Item, as well as reforging the item with new random modifiers", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 1000, 
		cost_sacred = 0, 
		command = "reroll_influence_types", 
		parameters = {"Claw",
"Dagger",
"Wand",
"One_Hand_Sword",
"Thrusting_One_Hand_Sword",
"One_Hand_Axe",
"One_Hand_Mace",
"Bow",
"Staff",
"Two_Hand_Sword",
"Two_Hand_Axe",
"Two_Hand_Mace",
"Rune_Dagger",
"Warstaff",
"Sceptre",
"Quiver",
"Gloves",
"Boots",
"Body_Armour",
"Helmet",
"Shield",
"Amulet",
"Ring",
"Belt"}, 
	},
	{
		id = "LifeBodyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Body Armour}}. Quality does not increase its Defences, grants {{c|white|+1 Maximum Life per 2% quality}}", 
		tier = 2, 
		effect = "Enchant a Body Armour. Quality does not increase its Defences, grants +1 Maximum Life per 2% quality", 
		is_enchant = true, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 3250, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Body_Armour",
"ENCHANTS",
"HarvestAlternateArmourQualityIncreasedLife"}, 
	},
	{
		id = "ManaBodyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Body Armour}}. Quality does not increase its Defences, grants {{c|white|+1 Maximum Mana per 2% quality}}", 
		tier = 2, 
		effect = "Enchant a Body Armour. Quality does not increase its Defences, grants +1 Maximum Mana per 2% quality", 
		is_enchant = true, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 3250, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Body_Armour",
"ENCHANTS",
"HarvestAlternateArmourQualityIncreasedMana"}, 
	},
	{
		id = "StrengthBodyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Body Armour}}. Quality does not increase its Defences, grants {{c|white|+1 Strength per 2% quality}}", 
		tier = 2, 
		effect = "Enchant a Body Armour. Quality does not increase its Defences, grants +1 Strength per 2% quality", 
		is_enchant = true, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 3250, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Body_Armour",
"ENCHANTS",
"HarvestAlternateArmourQualityStrength"}, 
	},
	{
		id = "DexterityBodyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Body Armour}}. Quality does not increase its Defences, grants {{c|white|+1 Dexterity per 2% quality}}", 
		tier = 2, 
		effect = "Enchant a Body Armour. Quality does not increase its Defences, grants +1 Dexterity per 2% quality", 
		is_enchant = true, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 3250, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Body_Armour",
"ENCHANTS",
"HarvestAlternateArmourQualityDexterity"}, 
	},
	{
		id = "IntelligenceBodyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Body Armour}}. Quality does not increase its Defences, grants {{c|white|+1 Intelligence per 2% quality}}", 
		tier = 2, 
		effect = "Enchant a Body Armour. Quality does not increase its Defences, grants +1 Intelligence per 2% quality", 
		is_enchant = true, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 3250, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Body_Armour",
"ENCHANTS",
"HarvestAlternateArmourQualityIntelligence_"}, 
	},
	{
		id = "FireResistBodyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Body Armour}}. Quality does not increase its Defences, grants {{c|white|+1% to Fire Resistance per 2% quality}}", 
		tier = 2, 
		effect = "Enchant a Body Armour. Quality does not increase its Defences, grants +1% to Fire Resistance per 2% quality", 
		is_enchant = true, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 3250, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Body_Armour",
"ENCHANTS",
"HarvestAlternateArmourQualityFireResistance"}, 
	},
	{
		id = "ColdResistBodyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Body Armour}}. Quality does not increase its Defences, grants {{c|white|+1% to Cold Resistance per 2% quality}}", 
		tier = 2, 
		effect = "Enchant a Body Armour. Quality does not increase its Defences, grants +1% to Cold Resistance per 2% quality", 
		is_enchant = true, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 3250, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Body_Armour",
"ENCHANTS",
"HarvestAlternateArmourQualityColdResistance"}, 
	},
	{
		id = "LightningResistBodyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Body Armour}}. Quality does not increase its Defences, grants {{c|white|+1% to Lightning Resistance per 2% quality}}", 
		tier = 2, 
		effect = "Enchant a Body Armour. Quality does not increase its Defences, grants +1% to Lightning Resistance per 2% quality", 
		is_enchant = true, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 3250, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Body_Armour",
"ENCHANTS",
"HarvestAlternateArmourQualityLightningResistance"}, 
	},
	{
		id = "WeaponRangeEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Melee Weapon}}. Quality does not increase its Physical Damage, has {{c|white|+1 Weapon Range per 10% Quality}}", 
		tier = 2, 
		effect = "Enchant a Melee Weapon. Quality does not increase its Physical Damage, has +1 Weapon Range per 10% Quality", 
		is_enchant = true, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 5000, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Claw",
"Dagger",
"One_Hand_Sword",
"Thrusting_One_Hand_Sword",
"One_Hand_Axe",
"One_Hand_Mace",
"Staff",
"Two_Hand_Sword",
"Two_Hand_Axe",
"Two_Hand_Mace",
"Rune_Dagger",
"Warstaff",
"Sceptre",
"ENCHANTS",
"HarvestAlternateWeaponQualityLocalMeleeWeaponRange_"}, 
	},
	{
		id = "WeaponAreaEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Weapon}}. Quality does not increase its Physical Damage, grants {{c|white|1% increased Area of Effect per 4% Quality}}", 
		tier = 2, 
		effect = "Enchant a Weapon. Quality does not increase its Physical Damage, grants 1% increased Area of Effect per 4% Quality", 
		is_enchant = true, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 5000, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Claw",
"Dagger",
"Wand",
"One_Hand_Sword",
"Thrusting_One_Hand_Sword",
"One_Hand_Axe",
"One_Hand_Mace",
"Bow",
"Staff",
"Two_Hand_Sword",
"Two_Hand_Axe",
"Two_Hand_Mace",
"Rune_Dagger",
"Warstaff",
"Sceptre",
"ENCHANTS",
"HarvestAlternateWeaponQualityAreaOfEffect_"}, 
	},
	{
		id = "WeaponAccuracyEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Weapon}}. Quality does not increase its Physical Damage, grants {{c|white|1% increased Accuracy per 2% Quality}}", 
		tier = 2, 
		effect = "Enchant a Weapon. Quality does not increase its Physical Damage, grants 1% increased Accuracy per 2% Quality", 
		is_enchant = true, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 5000, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Claw",
"Dagger",
"Wand",
"One_Hand_Sword",
"Thrusting_One_Hand_Sword",
"One_Hand_Axe",
"One_Hand_Mace",
"Bow",
"Staff",
"Two_Hand_Sword",
"Two_Hand_Axe",
"Two_Hand_Mace",
"Rune_Dagger",
"Warstaff",
"Sceptre",
"ENCHANTS",
"HarvestAlternateWeaponQualityAccuracyRatingIncrease_"}, 
	},
	{
		id = "WeaponAttackSpeedEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Weapon}}. Quality does not increase its Physical Damage, has {{c|white|1% increased Attack Speed per 8% Quality}}", 
		tier = 2, 
		effect = "Enchant a Weapon. Quality does not increase its Physical Damage, has 1% increased Attack Speed per 8% Quality", 
		is_enchant = true, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 5000, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Claw",
"Dagger",
"Wand",
"One_Hand_Sword",
"Thrusting_One_Hand_Sword",
"One_Hand_Axe",
"One_Hand_Mace",
"Bow",
"Staff",
"Two_Hand_Sword",
"Two_Hand_Axe",
"Two_Hand_Mace",
"Rune_Dagger",
"Warstaff",
"Sceptre",
"ENCHANTS",
"HarvestAlternateWeaponQualityLocalIncreasedAttackSpeed"}, 
	},
	{
		id = "WeaponCriticalEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Weapon}}. Quality does not increase its Physical Damage, has {{c|white|1% increased Critical Strike Chance per 4% Quality}}", 
		tier = 2, 
		effect = "Enchant a Weapon. Quality does not increase its Physical Damage, has 1% increased Critical Strike Chance per 4% Quality", 
		is_enchant = true, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 5000, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Claw",
"Dagger",
"Wand",
"One_Hand_Sword",
"Thrusting_One_Hand_Sword",
"One_Hand_Axe",
"One_Hand_Mace",
"Bow",
"Staff",
"Two_Hand_Sword",
"Two_Hand_Axe",
"Two_Hand_Mace",
"Rune_Dagger",
"Warstaff",
"Sceptre",
"ENCHANTS",
"HarvestAlternateWeaponQualityLocalCriticalStrikeChance__"}, 
	},
	{
		id = "WeaponElementalEnchant", 
		text = "{{c|white|Enchant}} a {{c|white|Weapon}}. Quality does not increase its Physical Damage, grants {{c|white|1% increased Elemental Damage per 2% Quality}}", 
		tier = 2, 
		effect = "Enchant a Weapon. Quality does not increase its Physical Damage, grants 1% increased Elemental Damage per 2% Quality", 
		is_enchant = true, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 5000, 
		cost_sacred = 0, 
		command = "add_enchant_to_class", 
		parameters = {"Claw",
"Dagger",
"Wand",
"One_Hand_Sword",
"Thrusting_One_Hand_Sword",
"One_Hand_Axe",
"One_Hand_Mace",
"Bow",
"Staff",
"Two_Hand_Sword",
"Two_Hand_Axe",
"Two_Hand_Mace",
"Rune_Dagger",
"Warstaff",
"Sceptre",
"ENCHANTS",
"HarvestAlternateWeaponQualityElementalDamagePercent"}, 
	},
	{
		id = "ReforgeWhiteSocket", 
		text = "{{c|white|Reforge}} the colour of a random {{c|white|socket}} on an item, turning it {{c|white|White}}", 
		tier = 2, 
		effect = "Reforge the colour of a random socket on an item, turning it White", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 12500, 
		cost_sacred = 1, 
		command = "modify_socket_colors", 
		parameters = {"W"}, 
	},
	{
		id = "AugmentFire", 
		text = "{{c|white|Add}} a new {{c|orange|Fire}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Fire modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 15000, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"fire",
"noinfluence"}, 
	},
	{
		id = "AugmentCold", 
		text = "{{c|white|Add}} a new {{c|blue|Cold}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Cold modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 15000, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"cold",
"noinfluence"}, 
	},
	{
		id = "AugmentLightning", 
		text = "{{c|white|Add}} a new {{c|yellow|Lightning}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Lightning modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 15000, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"lightning",
"noinfluence"}, 
	},
	{
		id = "AugmentPhysical", 
		text = "{{c|white|Add}} a new {{c|tan|Physical}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Physical modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 15000, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"physical",
"noinfluence"}, 
	},
	{
		id = "AugmentLife", 
		text = "{{c|white|Add}} a new {{c|red|Life}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Life modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 17500, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"life",
"noinfluence"}, 
	},
	{
		id = "AugmentDefences", 
		text = "{{c|white|Add}} a new {{c|white|Defence}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Defence modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 17500, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"defences",
"noinfluence"}, 
	},
	{
		id = "AugmentChaos", 
		text = "{{c|white|Add}} a new {{c|purple|Chaos}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Chaos modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 17500, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"chaos",
"noinfluence"}, 
	},
	{
		id = "AugmentAttack", 
		text = "{{c|white|Add}} a new {{c|white|Attack}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Attack modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 1, 
		cost_lifeforce = 17500, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"attack",
"noinfluence"}, 
	},
	{
		id = "AugmentSpell", 
		text = "{{c|white|Add}} a new {{c|purple|Caster}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Caster modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 17500, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"caster",
"noinfluence"}, 
	},
	{
		id = "AugmentSpeed", 
		text = "{{c|white|Add}} a new {{c|green|Speed}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Speed modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 20000, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"speed",
"noinfluence"}, 
	},
	{
		id = "AugmentCritical", 
		text = "{{c|white|Add}} a new {{c|blue|Critical}} modifier and {{c|white|remove}} another random modifier from a non-Influenced item", 
		tier = 2, 
		effect = "Add a new Critical modifier and remove another random modifier from a non-Influenced item", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 20000, 
		cost_sacred = 1, 
		command = "remove_type_and_add_type_mod", 
		parameters = {"ANY",
"FOR",
"critical",
"noinfluence"}, 
	},
	{
		id = "BossSynthesis1", 
		text = "{{c|white|Synthesise}} an item, giving random Synthesised implicits. Cannot be used on Unique, Influenced, Synthesised or Fractured items", 
		tier = 3, 
		effect = "Synthesise an item, giving random Synthesised implicits. Cannot be used on Unique, Influenced, Synthesised or Fractured items", 
		is_enchant = false, 
		cost_lifeforce_type = 2, 
		cost_lifeforce = 5000, 
		cost_sacred = 1, 
		command = "add_synthesized_implicits", 
		parameters = {"12",
"3",
"1"}, 
	},
	{
		id = "BossInfluence1", 
		text = "{{c|white|Reforge}} an {{c|white|Influenced}} Rare item with random modifiers, including a {{c|white|Influence}} modifier", 
		tier = 3, 
		effect = "Reforge an Influenced Rare item with random modifiers, including a Influence modifier", 
		is_enchant = false, 
		cost_lifeforce_type = 3, 
		cost_lifeforce = 5000, 
		cost_sacred = 1, 
		command = "reroll_with_influence_mod", 
	}}
return data