local data = {	{
		id = "Bunker", 
		area_ids = "HeistBunker1,HeistBunker2,HeistBunker3,HeistBunker4,HeistBunker5,HeistBunker6,HeistBunker7,HeistBunker8,HeistBunker9", 
		job_ids = "Lockpicking,Agility,Demolition,Engineering,CounterThaumaturge,Perception,TrapDisarmament", 
		contract_id = "Metadata/Items/Heist/HeistContractControlBlocks", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintControlBlocks", 
		reward_text = "Enchanted Armaments", 
	},
	{
		id = "Mines", 
		area_ids = "HeistMines1,HeistMines2,HeistMines3,HeistMines4,HeistMines5,HeistMines6,HeistMines7,HeistMines8,HeistMines9", 
		job_ids = "BruteForce,Perception,Demolition,TrapDisarmament,Deception", 
		contract_id = "Metadata/Items/Heist/HeistContractMines", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintMines", 
		reward_text = "Thieves' Trinkets or Currency", 
	},
	{
		id = "Dungeon", 
		area_ids = "HeistDungeon1,HeistDungeon2,HeistDungeon3,HeistDungeon4,HeistDungeon5,HeistDungeon6,HeistDungeon7,HeistDungeon8,HeistDungeon9", 
		job_ids = "Demolition,Perception,Engineering,Deception,CounterThaumaturge", 
		contract_id = "Metadata/Items/Heist/HeistContractDungeon", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintDungeon", 
		reward_text = "Replicas or Experimented Items", 
	},
	{
		id = "Reliquary", 
		area_ids = "HeistReliquary1,HeistReliquary2,HeistReliquary3,HeistReliquary4,HeistReliquary5,HeistReliquary6,HeistReliquary7,HeistReliquary8,HeistReliquary9", 
		job_ids = "Lockpicking,Perception,Agility,TrapDisarmament,Demolition", 
		contract_id = "Metadata/Items/Heist/HeistContractReliquary", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintReliquary", 
		reward_text = "Unusual Gems", 
	},
	{
		id = "Library", 
		area_ids = "HeistLibrary1,HeistLibrary2,HeistLibrary3,HeistLibrary4_,HeistLibrary5,HeistLibrary6,HeistLibrary7,HeistLibrary8_,HeistLibrary9", 
		job_ids = "Lockpicking,Engineering,CounterThaumaturge,Perception,Deception", 
		contract_id = "Metadata/Items/Heist/HeistContractLibrary", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintLibrary", 
		reward_text = "Replicas or Experimented Items", 
	},
	{
		id = "RobotTunnels", 
		area_ids = "HeistRobotTunnels1,HeistRobotTunnels2,HeistRobotTunnels3,HeistRobotTunnels4,HeistRobotTunnels5,HeistRobotTunnels6,HeistRobotTunnels7,HeistRobotTunnels8,HeistRobotTunnels9", 
		job_ids = "BruteForce,Agility,Demolition,Engineering,CounterThaumaturge,TrapDisarmament", 
		contract_id = "Metadata/Items/Heist/HeistContractRobotTunnels", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintRobotTunnels", 
		reward_text = "Unusual Gems", 
	},
	{
		id = "Sewers", 
		area_ids = "HeistSewers1,HeistSewers2,HeistSewers3,HeistSewers4,HeistSewers5,HeistSewers6,HeistSewers7,HeistSewers8,HeistSewers9", 
		job_ids = "BruteForce,Agility,Demolition,Engineering,Deception", 
		contract_id = "Metadata/Items/Heist/HeistContractSewers", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintSewers", 
		reward_text = "Thieves' Trinkets or Currency", 
	},
	{
		id = "Courts", 
		area_ids = "HeistCourts1,HeistCourts2,HeistCourts3,HeistCourts4,HeistCourts5,HeistCourts6,HeistCourts7,HeistCourts8,HeistCourts9_", 
		job_ids = "Lockpicking,Demolition,TrapDisarmament,CounterThaumaturge,Deception,BruteForce", 
		contract_id = "Metadata/Items/Heist/HeistContractCourts", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintCourts", 
		reward_text = "Enchanted Armaments", 
	},
	{
		id = "Mansion", 
		area_ids = "HeistMansion1,HeistMansion2,HeistMansion3,HeistMansion4,HeistMansion5,HeistMansion6,HeistMansion7,HeistMansion8,HeistMansion9", 
		job_ids = "Lockpicking,Agility,Perception,Deception,BruteForce", 
		contract_id = "Metadata/Items/Heist/HeistContractMansion", 
		blueprint_id = "Metadata/Items/Heist/HeistBlueprintMansion", 
		reward_text = "Enchanted Armaments", 
	}}
return data