local data = {	{
		id = "None", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "Fire1", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 20, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 40, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "Cold1", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 20, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 40, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "Lightning1", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 20, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 40, 
		maps_chaos = 0, 
	},
	{
		id = "Chaos1", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 20, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 40, 
	},
	{
		id = "FireChaos1", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 15, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 15, 
		maps_fire = 30, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 30, 
	},
	{
		id = "ColdLightning1", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 15, 
		part2_lightning = 15, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 30, 
		maps_lightning = 30, 
		maps_chaos = 0, 
	},
	{
		id = "ColdChaos1", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 15, 
		part2_lightning = 0, 
		part2_chaos = 15, 
		maps_fire = 0, 
		maps_cold = 30, 
		maps_lightning = 0, 
		maps_chaos = 30, 
	},
	{
		id = "Elemental1", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 10, 
		part2_cold = 10, 
		part2_lightning = 10, 
		part2_chaos = 0, 
		maps_fire = 20, 
		maps_cold = 20, 
		maps_lightning = 20, 
		maps_chaos = 0, 
	},
	{
		id = "Fire1b", 
		part1_fire = 10, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 20, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 40, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "Cold1b", 
		part1_fire = 0, 
		part1_cold = 10, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 20, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 40, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "Lightning1b", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 10, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 20, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 40, 
		maps_chaos = 0, 
	},
	{
		id = "LightningChaos1b", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 7, 
		part1_chaos = 7, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 15, 
		part2_chaos = 15, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 30, 
		maps_chaos = 30, 
	},
	{
		id = "Chaos1b", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 10, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 20, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 40, 
	},
	{
		id = "FireChaos1b", 
		part1_fire = 7, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 7, 
		part2_fire = 15, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 15, 
		maps_fire = 30, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 30, 
	},
	{
		id = "ColdLightning1b", 
		part1_fire = 0, 
		part1_cold = 7, 
		part1_lightning = 7, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 15, 
		part2_lightning = 15, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 30, 
		maps_lightning = 30, 
		maps_chaos = 0, 
	},
	{
		id = "ColdChaos1b", 
		part1_fire = 0, 
		part1_cold = 7, 
		part1_lightning = 0, 
		part1_chaos = 7, 
		part2_fire = 0, 
		part2_cold = 15, 
		part2_lightning = 0, 
		part2_chaos = 15, 
		maps_fire = 0, 
		maps_cold = 30, 
		maps_lightning = 0, 
		maps_chaos = 30, 
	},
	{
		id = "Elemental1b", 
		part1_fire = 5, 
		part1_cold = 5, 
		part1_lightning = 5, 
		part1_chaos = 0, 
		part2_fire = 10, 
		part2_cold = 10, 
		part2_lightning = 10, 
		part2_chaos = 0, 
		maps_fire = 20, 
		maps_cold = 20, 
		maps_lightning = 20, 
		maps_chaos = 0, 
	},
	{
		id = "Fire2", 
		part1_fire = 20, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 45, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 75, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "Cold2", 
		part1_fire = 0, 
		part1_cold = 20, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 45, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 75, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "Lightning2", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 20, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 45, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 75, 
		maps_chaos = 0, 
	},
	{
		id = "Chaos2", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 20, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 45, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 75, 
	},
	{
		id = "FireCold2", 
		part1_fire = 15, 
		part1_cold = 15, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 34, 
		part2_cold = 34, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 52, 
		maps_cold = 52, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "ColdLightning2", 
		part1_fire = 0, 
		part1_cold = 15, 
		part1_lightning = 15, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 34, 
		part2_lightning = 34, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 52, 
		maps_lightning = 52, 
		maps_chaos = 0, 
	},
	{
		id = "Elemental2", 
		part1_fire = 10, 
		part1_cold = 10, 
		part1_lightning = 10, 
		part1_chaos = 0, 
		part2_fire = 23, 
		part2_cold = 23, 
		part2_lightning = 23, 
		part2_chaos = 0, 
		maps_fire = 37, 
		maps_cold = 37, 
		maps_lightning = 37, 
		maps_chaos = 0, 
	},
	{
		id = "ColdChaos2", 
		part1_fire = 0, 
		part1_cold = 15, 
		part1_lightning = 0, 
		part1_chaos = 15, 
		part2_fire = 0, 
		part2_cold = 34, 
		part2_lightning = 0, 
		part2_chaos = 34, 
		maps_fire = 0, 
		maps_cold = 52, 
		maps_lightning = 0, 
		maps_chaos = 52, 
	},
	{
		id = "FireBoss", 
		part1_fire = 25, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 55, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 85, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "ColdBoss", 
		part1_fire = 0, 
		part1_cold = 25, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 55, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 85, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "LightningBoss", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 25, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 55, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 85, 
		maps_chaos = 0, 
	},
	{
		id = "ChaosBoss", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 25, 
		part2_fire = 0, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 55, 
		maps_fire = 0, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 85, 
	},
	{
		id = "FireColdBoss", 
		part1_fire = 19, 
		part1_cold = 19, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 41, 
		part2_cold = 41, 
		part2_lightning = 0, 
		part2_chaos = 0, 
		maps_fire = 64, 
		maps_cold = 64, 
		maps_lightning = 0, 
		maps_chaos = 0, 
	},
	{
		id = "FireChaosBoss", 
		part1_fire = 19, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 19, 
		part2_fire = 41, 
		part2_cold = 0, 
		part2_lightning = 0, 
		part2_chaos = 41, 
		maps_fire = 64, 
		maps_cold = 0, 
		maps_lightning = 0, 
		maps_chaos = 64, 
	},
	{
		id = "ColdLightningBoss", 
		part1_fire = 0, 
		part1_cold = 19, 
		part1_lightning = 19, 
		part1_chaos = 0, 
		part2_fire = 0, 
		part2_cold = 41, 
		part2_lightning = 41, 
		part2_chaos = 0, 
		maps_fire = 0, 
		maps_cold = 64, 
		maps_lightning = 64, 
		maps_chaos = 0, 
	},
	{
		id = "ColdChaosBoss", 
		part1_fire = 0, 
		part1_cold = 19, 
		part1_lightning = 0, 
		part1_chaos = 19, 
		part2_fire = 0, 
		part2_cold = 41, 
		part2_lightning = 0, 
		part2_chaos = 41, 
		maps_fire = 0, 
		maps_cold = 64, 
		maps_lightning = 0, 
		maps_chaos = 64, 
	},
	{
		id = "ElementalBoss", 
		part1_fire = 12, 
		part1_cold = 12, 
		part1_lightning = 12, 
		part1_chaos = 0, 
		part2_fire = 27, 
		part2_cold = 27, 
		part2_lightning = 27, 
		part2_chaos = 0, 
		maps_fire = 42, 
		maps_cold = 42, 
		maps_lightning = 42, 
		maps_chaos = 0, 
	},
	{
		id = "MapBoss", 
		part1_fire = 15, 
		part1_cold = 15, 
		part1_lightning = 15, 
		part1_chaos = 7, 
		part2_fire = 30, 
		part2_cold = 30, 
		part2_lightning = 30, 
		part2_chaos = 20, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 25, 
	},
	{
		id = "MapBossSuper", 
		part1_fire = 15, 
		part1_cold = 15, 
		part1_lightning = 15, 
		part1_chaos = 7, 
		part2_fire = 30, 
		part2_cold = 30, 
		part2_lightning = 30, 
		part2_chaos = 20, 
		maps_fire = 50, 
		maps_cold = 50, 
		maps_lightning = 50, 
		maps_chaos = 30, 
	},
	{
		id = "SubBoss", 
		part1_fire = 10, 
		part1_cold = 10, 
		part1_lightning = 10, 
		part1_chaos = 5, 
		part2_fire = 20, 
		part2_cold = 20, 
		part2_lightning = 20, 
		part2_chaos = 12, 
		maps_fire = 30, 
		maps_cold = 30, 
		maps_lightning = 30, 
		maps_chaos = 20, 
	},
	{
		id = "SideAreaBoss", 
		part1_fire = 10, 
		part1_cold = 10, 
		part1_lightning = 10, 
		part1_chaos = 5, 
		part2_fire = 20, 
		part2_cold = 20, 
		part2_lightning = 20, 
		part2_chaos = 12, 
		maps_fire = 30, 
		maps_cold = 30, 
		maps_lightning = 30, 
		maps_chaos = 20, 
	},
	{
		id = "ActBoss", 
		part1_fire = 15, 
		part1_cold = 15, 
		part1_lightning = 15, 
		part1_chaos = 7, 
		part2_fire = 30, 
		part2_cold = 30, 
		part2_lightning = 30, 
		part2_chaos = 20, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 25, 
	},
	{
		id = "Totem", 
		part1_fire = 40, 
		part1_cold = 40, 
		part1_lightning = 40, 
		part1_chaos = 20, 
		part2_fire = 40, 
		part2_cold = 40, 
		part2_lightning = 40, 
		part2_chaos = 20, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 20, 
	},
	{
		id = "MinionZombie", 
		part1_fire = 40, 
		part1_cold = 40, 
		part1_lightning = 40, 
		part1_chaos = 20, 
		part2_fire = 40, 
		part2_cold = 40, 
		part2_lightning = 40, 
		part2_chaos = 20, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 20, 
	},
	{
		id = "MinionGeneric", 
		part1_fire = 40, 
		part1_cold = 40, 
		part1_lightning = 40, 
		part1_chaos = 20, 
		part2_fire = 40, 
		part2_cold = 40, 
		part2_lightning = 40, 
		part2_chaos = 20, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 20, 
	},
	{
		id = "MinionFlameGolem", 
		part1_fire = 70, 
		part1_cold = 40, 
		part1_lightning = 40, 
		part1_chaos = 20, 
		part2_fire = 70, 
		part2_cold = 40, 
		part2_lightning = 40, 
		part2_chaos = 20, 
		maps_fire = 70, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 20, 
	},
	{
		id = "MinionIceGolem", 
		part1_fire = 40, 
		part1_cold = 70, 
		part1_lightning = 40, 
		part1_chaos = 20, 
		part2_fire = 40, 
		part2_cold = 70, 
		part2_lightning = 40, 
		part2_chaos = 20, 
		maps_fire = 40, 
		maps_cold = 70, 
		maps_lightning = 40, 
		maps_chaos = 20, 
	},
	{
		id = "MinionLightningGolem", 
		part1_fire = 40, 
		part1_cold = 40, 
		part1_lightning = 70, 
		part1_chaos = 20, 
		part2_fire = 40, 
		part2_cold = 40, 
		part2_lightning = 70, 
		part2_chaos = 20, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 70, 
		maps_chaos = 20, 
	},
	{
		id = "MinonStoneGolem", 
		part1_fire = 40, 
		part1_cold = 40, 
		part1_lightning = 40, 
		part1_chaos = 20, 
		part2_fire = 40, 
		part2_cold = 40, 
		part2_lightning = 40, 
		part2_chaos = 20, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 20, 
	},
	{
		id = "MinionChaosGolem", 
		part1_fire = 40, 
		part1_cold = 40, 
		part1_lightning = 40, 
		part1_chaos = 60, 
		part2_fire = 40, 
		part2_cold = 40, 
		part2_lightning = 40, 
		part2_chaos = 60, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 60, 
	},
	{
		id = "ElementalChaos", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 20, 
		part2_cold = 20, 
		part2_lightning = 20, 
		part2_chaos = 12, 
		maps_fire = 35, 
		maps_cold = 35, 
		maps_lightning = 35, 
		maps_chaos = 20, 
	},
	{
		id = "BestiaryLegendary", 
		part1_fire = 0, 
		part1_cold = 0, 
		part1_lightning = 0, 
		part1_chaos = 0, 
		part2_fire = 25, 
		part2_cold = 25, 
		part2_lightning = 25, 
		part2_chaos = 15, 
		maps_fire = 40, 
		maps_cold = 40, 
		maps_lightning = 40, 
		maps_chaos = 25, 
	}}
return data