local data = {	{
		name = "Monster", 
		id = "item_drop_slots", 
		value = 1, 
		stat_text = "1 item drop slots", 
	},
	{
		name = "Monster", 
		id = "energy_shield_recharge_rate_per_minute_%", 
		value = 2000, 
		stat_text = "33.3% of [[Energy Shield]] Recharged per second", 
	},
	{
		name = "Monster", 
		id = "mana_regeneration_rate_per_minute_%", 
		value = 100, 
		stat_text = "Regenerate 1.7% of [[Mana]] per second", 
	},
	{
		name = "Monster", 
		id = "base_maximum_mana", 
		value = 200, 
		stat_text = "+200 to maximum [[Mana]]", 
	},
	{
		name = "Monster", 
		id = "maximum_physical_damage_reduction_%", 
		value = 75, 
		stat_text = "75% to maximum [[Physical Damage]] Reduction", 
	},
	{
		name = "Monster", 
		id = "max_viper_strike_orbs", 
		value = 4, 
		stat_text = "Can have up to 4 [[Viper Strike]] Orbs", 
	},
	{
		name = "Monster", 
		id = "base_maximum_all_resistances_%", 
		value = 75, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "max_fuse_arrow_orbs", 
		value = 5, 
		stat_text = "Can have up to 5 [[Explosive Arrow]] Stacks", 
	},
	{
		name = "Monster", 
		id = "max_fire_beam_stacks", 
		value = 8, 
		stat_text = "Can have up to 8 Fire Beam Stacks", 
	},
	{
		name = "Monster", 
		id = "max_charged_attack_stacks", 
		value = 10, 
		stat_text = "10 additional maximum [[Blade Flurry]] stages", 
	},
	{
		name = "Monster", 
		id = "base_critical_strike_multiplier", 
		value = 130, 
		stat_text = "Base [[Critical Strike]] Multiplier: 130", 
	},
	{
		name = "Monster", 
		id = "critical_ailment_dot_multiplier_+", 
		value = 30, 
		stat_text = "+30% to Damage over Time Multiplier for Ailments from Critical Strikes", 
	},
	{
		name = "Monster", 
		id = "max_endurance_charges", 
		value = 3, 
		stat_text = "+3 to Maximum [[Endurance Charge|Endurance Charges]]", 
	},
	{
		name = "Monster", 
		id = "max_frenzy_charges", 
		value = 3, 
		stat_text = "+3 to Maximum [[Frenzy Charge|Frenzy Charges]]", 
	},
	{
		name = "Monster", 
		id = "max_power_charges", 
		value = 3, 
		stat_text = "+3 to Maximum [[Power Charge|Power Charges]]", 
	},
	{
		name = "Monster", 
		id = "base_attack_speed_+%_per_frenzy_charge", 
		value = 4, 
		stat_text = "4% increased [[Attack Speed]] per [[Frenzy Charge]]", 
	},
	{
		name = "Monster", 
		id = "base_attack_speed_+%_per_frenzy_charge_if_not_player_minion", 
		value = 11, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "base_cast_speed_+%_per_frenzy_charge", 
		value = 4, 
		stat_text = "4% increased [[Cast Speed]] per [[Frenzy Charge]]", 
	},
	{
		name = "Monster", 
		id = "base_cast_speed_+%_per_frenzy_charge_if_not_player_minion", 
		value = 11, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "movement_velocity_+%_per_frenzy_charge_if_not_player_minion", 
		value = 5, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "object_inherent_damage_+%_final_per_frenzy_charge", 
		value = 4, 
		stat_text = "4% more Damage per [[Frenzy Charge]]", 
	},
	{
		name = "Monster", 
		id = "physical_damage_reduction_%_per_endurance_charge", 
		value = 4, 
		stat_text = "4% additional [[Physical Damage]] Reduction per [[Endurance Charge]]", 
	},
	{
		name = "Monster", 
		id = "physical_damage_reduction_%_per_endurance_charge_if_not_player_minion", 
		value = 11, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "resist_all_elements_%_per_endurance_charge", 
		value = 4, 
		stat_text = "+4% to all [[Elemental Resistance|Elemental Resistances]] per [[Endurance Charge]]", 
	},
	{
		name = "Monster", 
		id = "resist_all_elements_%_per_endurance_charge_if_not_player_minion", 
		value = 11, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "critical_strike_chance_+%_per_power_charge", 
		value = 50, 
		stat_text = "50% increased [[Critical Strike Chance]] per [[Power Charge]]", 
	},
	{
		name = "Monster", 
		id = "critical_strike_chance_+%_per_power_charge_if_not_player_minion", 
		value = 150, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "maximum_block_%", 
		value = 75, 
		stat_text = "+75% to maximum Chance to [[Block]] [[Attack Damage]]", 
	},
	{
		name = "Monster", 
		id = "base_maximum_spell_block_%", 
		value = 75, 
		stat_text = "+75% to maximum Chance to [[Block]] [[Spell Damage]]", 
	},
	{
		name = "Monster", 
		id = "base_number_of_totems_allowed", 
		value = 1, 
		stat_text = "+1 to maximum number of Summoned [[Totem|Totems]]", 
	},
	{
		name = "Monster", 
		id = "base_number_of_traps_allowed", 
		value = 3, 
		stat_text = "Can have up to 3 [[Trap|Traps]] placed at a time", 
	},
	{
		name = "Monster", 
		id = "base_number_of_remote_mines_allowed", 
		value = 5, 
		stat_text = "Can have up to 5 Remote [[Mine|Mines]] placed at a time", 
	},
	{
		name = "Monster", 
		id = "movement_velocity_cap", 
		value = 128, 
		stat_text = "[[Movement Speed]] is capped at 128", 
	},
	{
		name = "Monster", 
		id = "maximum_life_leech_rate_%_per_minute", 
		value = 1200, 
		stat_text = "+20% to Maximum total [[Life]] Recovery per second from [[Leech]]", 
	},
	{
		name = "Monster", 
		id = "maximum_mana_leech_rate_%_per_minute", 
		value = 1200, 
		stat_text = "+20% Maximum total [[Mana]] Recovery per second from [[Leech]]", 
	},
	{
		name = "Monster", 
		id = "maximum_energy_shield_leech_rate_%_per_minute", 
		value = 600, 
		stat_text = "+10% to Maximum total [[Energy Shield]] Recovery per second from [[Leech]]", 
	},
	{
		name = "Monster", 
		id = "monster_ignite_damage_+%_final", 
		value = -72, 
		stat_text = "Monsters deal 72% less [[Ignite]] Damage", 
	},
	{
		name = "Monster", 
		id = "monster_bleeding_damage_+%_final", 
		value = -86, 
		stat_text = "Monsters deal 86% less Bleeding Damage", 
	},
	{
		name = "Monster", 
		id = "monster_poison_damage_+%_final", 
		value = -50, 
		stat_text = "Monsters deal 50% less [[Poison]] Damage", 
	},
	{
		name = "Monster", 
		id = "bleeding_moving_damage_%_of_base_override", 
		value = 500, 
		stat_text = "Bleeding while moving deals 500% of base damage", 
	},
	{
		name = "Monster", 
		id = "max_azurite_debuff_stacks", 
		value = 10, 
		stat_text = "Can have up to 10 Azurite Stacks", 
	},
	{
		name = "Monster", 
		id = "impaled_debuff_base_duration_ms", 
		value = 8000, 
		stat_text = "Impale lasts 8 seconds", 
	},
	{
		name = "Monster", 
		id = "impaled_debuff_number_of_reflected_hits", 
		value = 5, 
		stat_text = "Impales you inflict last 5 additional [[Hit|Hits]]", 
	},
	{
		name = "Monster", 
		id = "ignore_skill_weapon_restrictions", 
		value = 1, 
		stat_text = "[[Skill]] weapon restrictions are ignored", 
	},
	{
		name = "Monster", 
		id = "base_total_number_of_sigils_allowed", 
		value = 3, 
		stat_text = "You can Cast 3 additional Brands", 
	},
	{
		name = "Monster", 
		id = "maximum_life_leech_amount_per_leech_%_max_life", 
		value = 10, 
		stat_text = "+10% of Maximum [[Life]] to maximum Recovery per [[Life]] [[Leech]]", 
	},
	{
		name = "Monster", 
		id = "maximum_mana_leech_amount_per_leech_%_max_mana", 
		value = 10, 
		stat_text = "+10% of Maximum [[Mana]] to maximum Recovery per [[Mana]] [[Leech]]", 
	},
	{
		name = "Monster", 
		id = "maximum_energy_shield_leech_amount_per_leech_%_max_energy_shield", 
		value = 10, 
		stat_text = "+10% of Maximum [[Energy Shield]] to maximum Recovery per [[Energy Shield]] [[Leech]]", 
	},
	{
		name = "Monster", 
		id = "object_inherent_melee_hit_stun_duration_+%_final", 
		value = 20, 
		stat_text = "Melee [[Hit|hits]] have 20% more Stun Duration", 
	},
	{
		name = "Monster", 
		id = "scale_melee_range_to_actor_scale", 
		value = 1, 
		stat_text = "Melee range scaled by model size", 
	},
	{
		name = "Monster", 
		id = "use_melee_pattern_range", 
		value = 1, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "actor_scale_+%_limit", 
		value = 200, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "damage_taken_when_hit_+%_final_per_fortification", 
		value = -1, 
		stat_text = "", 
	},
	{
		name = "Monster", 
		id = "base_max_fortification", 
		value = 20, 
		stat_text = "+20 to maximum Fortification", 
	}}
return data