local data = {	{
		level = 66, 
		life = 1, 
		damage = 0, 
		boss_life = 50, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 67, 
		life = 3, 
		damage = 0, 
		boss_life = 52, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 68, 
		life = 5, 
		damage = 0, 
		boss_life = 54, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 69, 
		life = 9, 
		damage = 1, 
		boss_life = 56, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 70, 
		life = 13, 
		damage = 2, 
		boss_life = 58, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 71, 
		life = 19, 
		damage = 3, 
		boss_life = 60, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 72, 
		life = 24, 
		damage = 4, 
		boss_life = 62, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 73, 
		life = 30, 
		damage = 5, 
		boss_life = 64, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 74, 
		life = 36, 
		damage = 6, 
		boss_life = 66, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 75, 
		life = 43, 
		damage = 7, 
		boss_life = 68, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 76, 
		life = 49, 
		damage = 8, 
		boss_life = 70, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 77, 
		life = 55, 
		damage = 9, 
		boss_life = 72, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 78, 
		life = 61, 
		damage = 10, 
		boss_life = 74, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 79, 
		life = 68, 
		damage = 11, 
		boss_life = 76, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 80, 
		life = 77, 
		damage = 12, 
		boss_life = 78, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 81, 
		life = 87, 
		damage = 13, 
		boss_life = 80, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 82, 
		life = 98, 
		damage = 14, 
		boss_life = 82, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 83, 
		life = 109, 
		damage = 15, 
		boss_life = 84, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 84, 
		life = 117, 
		damage = 16, 
		boss_life = 86, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 85, 
		life = 125, 
		damage = 17, 
		boss_life = 88, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 86, 
		life = 134, 
		damage = 18, 
		boss_life = 90, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 87, 
		life = 142, 
		damage = 19, 
		boss_life = 92, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 88, 
		life = 150, 
		damage = 20, 
		boss_life = 94, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 89, 
		life = 158, 
		damage = 21, 
		boss_life = 96, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		level = 90, 
		life = 166, 
		damage = 22, 
		boss_life = 98, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 100, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 102, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 104, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 106, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 108, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 110, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 112, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 114, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 116, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 118, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 120, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 122, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 124, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 126, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 128, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 130, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 132, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 134, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 136, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 138, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 140, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 142, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 144, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 146, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 148, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 150, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 152, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 154, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 156, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 158, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 160, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 162, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 164, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 166, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 168, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 170, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 172, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 174, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 176, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 178, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 180, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 180, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 180, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 203, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 216, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 232, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 248, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 463, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 497, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 532, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 566, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 599, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 946, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 1032, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 1201, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 1443, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 1620, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 1864, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 2046, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 2046, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 2046, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 2046, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 2046, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 2046, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	},
	{
		boss_life = 2046, 
		boss_damage = 0, 
		boss_item_quantity = 0, 
		boss_item_rarity = 0, 
	}}
return data