local data = {	{
		id = "TheBrineKing", 
		ordinal = 1, 
		name = "Soul of the Brine King", 
		stat_text = "You cannot be Stunned if you've been Stunned or Blocked a Stunning [[Hit]] in the past 2 seconds", 
	},
	{
		id = "TheBrineKing", 
		ordinal = 2, 
		name = "Puruna, the Challenger", 
		stat_text = "30% increased Stun and [[Block]] Recovery", 
		target_area_id = "MapWorldsAtoll", 
		target_monster_id = "Metadata/Monsters/Totems/TotemMapBossCold", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulBrineKingUpgrade1", 
	},
	{
		id = "TheBrineKing", 
		ordinal = 3, 
		name = "Fragment of Winter", 
		stat_text = "100% chance to Avoid being [[Freeze|Frozen]]", 
		target_area_id = "MapWorldsWaterways", 
		target_monster_id = "Metadata/Monsters/IceElemental/IceElementalMapBoss", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulBrineKingUpgrade2", 
	},
	{
		id = "TheBrineKing", 
		ordinal = 4, 
		name = "Pirate Treasure", 
		stat_text = "50% reduced Effect of Chill on you", 
		target_area_id = "MapWorldsCoves", 
		target_monster_id = "Metadata/Monsters/RockGolem/TreasureGolemMapBossSimplified", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulBrineKingUpgrade3", 
	},
	{
		id = "Arakaali", 
		ordinal = 1, 
		name = "Soul of Arakaali", 
		stat_text = "10% reduced Damage taken from Damage Over Time", 
	},
	{
		id = "Arakaali", 
		ordinal = 2, 
		name = "Maligaro the Mutilator", 
		stat_text = "20% increased Recovery rate of [[Life]] and [[Energy Shield]] if you've stopped taking Damage Over Time [[Recently]]", 
		target_area_id = "MapWorldsOvergrownShrine", 
		target_monster_id = "Metadata/Monsters/Maligaro/MaligaroSoulMap", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulArakaaliUpgrade1", 
	},
	{
		id = "Arakaali", 
		ordinal = 3, 
		name = "Hybrid Widow", 
		stat_text = "Debuffs on you expire 20% faster", 
		target_area_id = "MapWorldsArachnidTomb", 
		target_monster_id = "Metadata/Monsters/Spiders/MapSpiderBossSinsSimplified", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulArakaaliUpgrade2", 
	},
	{
		id = "Arakaali", 
		ordinal = 4, 
		name = "Armala, the Widow", 
		stat_text = "+40% [[Chaos Resistance]] against Damage Over Time", 
		target_area_id = "MapWorldsSunkenCity", 
		target_monster_id = "Metadata/Monsters/VaalSpiderGod/ArakaaliMap", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulArakaaliUpgrade3", 
	},
	{
		id = "Solaris", 
		ordinal = 1, 
		name = "Soul of Solaris", 
		stat_text = "6% additional [[Physical Damage]] Reduction while there<br>is only one nearby Enemy<br>20% chance to take 50% less Area Damage from [[Hit|Hits]]", 
	},
	{
		id = "Solaris", 
		ordinal = 2, 
		name = "A Redblade Warlord", 
		stat_text = "8% reduced [[Elemental Damage]] taken if you haven't<br>been [[Hit]] [[Recently]]", 
		target_area_id = "MapWorldsVolcano", 
		target_monster_id = "Metadata/Monsters/Totems/PuiTotemMapBoss_", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulSolarisUpgrade1", 
	},
	{
		id = "Solaris", 
		ordinal = 3, 
		name = "Fire and Fury", 
		stat_text = "Take no Extra Damage from Critical Strikes if you have taken a [[Critical Strike]] [[Recently]]", 
		target_area_id = "MapWorldsLavaChamber", 
		target_monster_id = "Metadata/Monsters/Seawitch/MapSeaWitchBossFirestorm", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulSolarisUpgrade2", 
	},
	{
		id = "Solaris", 
		ordinal = 4, 
		name = "Jorus, Sky's Edge", 
		stat_text = "50% chance to avoid Ailments from Critical Strikes", 
		target_area_id = "MapWorldsTemple", 
		target_monster_id = "Metadata/Monsters/GuardianOfSolaris/GuardianOfSolarisMap", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulSolarisUpgrade3", 
	},
	{
		id = "Lunaris", 
		ordinal = 1, 
		name = "Soul of Lunaris", 
		stat_text = "1% additional [[Physical Damage]] Reduction for each<br>nearby Enemy, up to 8%<br>1% increased [[Movement Speed]] for each<br>nearby Enemy, up to 8%", 
	},
	{
		id = "Lunaris", 
		ordinal = 2, 
		name = "Khor, Sister of Shadows", 
		stat_text = "10% chance to avoid Projectiles", 
		target_area_id = "MapWorldsColdRiver_", 
		target_monster_id = "Metadata/Monsters/LunarisSolaris/LunarisMap", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulLunarisUpgrade1", 
	},
	{
		id = "Lunaris", 
		ordinal = 3, 
		name = "Captain Clayborne, The Accursed", 
		stat_text = "6% reduced [[Elemental Damage]] taken if you have been [[Hit]] [[Recently]]", 
		target_area_id = "MapWorldsFrozenCabins", 
		target_monster_id = "Metadata/Monsters/Skeletons/Pirate/BrutalPirateLordBoss", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulLunarisUpgrade2", 
	},
	{
		id = "Lunaris", 
		ordinal = 4, 
		name = "The Winged Death", 
		stat_text = "Avoid Projectiles that have Chained", 
		target_area_id = "MapWorldsChannel", 
		target_monster_id = "Metadata/Monsters/VultureParasite/VultureParasiteMapBoss", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulLunarisUpgrade3", 
	},
	{
		id = "Abberath", 
		ordinal = 1, 
		name = "Soul of Abberath", 
		stat_text = "60% less Duration of [[Ignite]] on You", 
	},
	{
		id = "Abberath", 
		ordinal = 2, 
		name = "Mephod, the Earth Scorcher", 
		stat_text = "Unaffected by Burning Ground<br>10% increased [[Movement Speed]] while on Burning Ground", 
		target_area_id = "MapWorldsSummit", 
		target_monster_id = "Metadata/Monsters/Abberath/Abberath2Map", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulAbberathUpgrade1", 
	},
	{
		id = "Gruthkul", 
		ordinal = 1, 
		name = "Soul of Gruthkul", 
		stat_text = "1% additional [[Physical Damage]] Reduction for each [[Hit]] you've taken [[Recently]] up to a maximum of 5%", 
	},
	{
		id = "Gruthkul", 
		ordinal = 2, 
		name = "Erebix, Light's Bane", 
		stat_text = "Enemies that have [[Hit]] you with an [[Attack]] [[Recently]] have 8% reduced [[Attack Speed]]", 
		target_area_id = "MapWorldsCemetery", 
		target_monster_id = "Metadata/Monsters/DespairBear/DespairBearMap", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulGruthkulUpgrade1", 
	},
	{
		id = "Yugul", 
		ordinal = 1, 
		name = "Soul of Yugul", 
		stat_text = "You and your [[Minion|Minions]] take 50% reduced Reflected Damage<br>50% chance to Reflect Hexes", 
	},
	{
		id = "Yugul", 
		ordinal = 2, 
		name = "Varhesh, Shimmering Aberration", 
		stat_text = "30% reduced Effect of [[Curse|Curses]] on you", 
		target_area_id = "MapWorldsTerrace", 
		target_monster_id = "Metadata/Monsters/Frog/FrogGod/SilverFrogMap", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulYugulUpgrade1", 
	},
	{
		id = "Shakari", 
		ordinal = 1, 
		name = "Soul of Shakari", 
		stat_text = "50% less Duration of [[Poison|Poisons]] on You<br>You cannot be [[Poison|Poisoned]] while there are at least 3 [[Poison|Poisons]] on you", 
	},
	{
		id = "Shakari", 
		ordinal = 2, 
		name = "Avatar of Undoing", 
		stat_text = "5% reduced [[Chaos Damage]] taken<br>25% reduced [[Chaos Damage]] over Time taken while on Caustic Ground", 
		target_area_id = "MapWorldsGeode", 
		target_monster_id = "Metadata/Monsters/ChaosElemental/ChaosElementalMapBoss2", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulShakariUpgrade1", 
	},
	{
		id = "Tukohama", 
		ordinal = 1, 
		name = "Soul of Tukohama", 
		stat_text = "3% additional [[Physical Damage]] Reduction per second you've been stationary, up to a maximum of 9%", 
	},
	{
		id = "Tukohama", 
		ordinal = 2, 
		name = "Tahsin, Warmaker", 
		stat_text = "Regenerate 2% of [[Life]] per second while stationary", 
		target_area_id = "MapWorldsSiege", 
		target_monster_id = "Metadata/Monsters/Tukohama/TukohamaMap", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulTukohamaUpgrade1", 
	},
	{
		id = "Ralakesh", 
		ordinal = 1, 
		name = "Soul of Ralakesh", 
		stat_text = "25% reduced [[Physical Damage]] over Time taken while moving<br>Moving while Bleeding doesn't cause you to take extra Damage", 
	},
	{
		id = "Ralakesh", 
		ordinal = 2, 
		name = "The Hollow Lady", 
		stat_text = "[[Corrupted Blood]] cannot be inflicted on you if you have at least 5 [[Corrupted Blood]] Debuffs on you", 
		target_area_id = "MapWorldsVaalPyramid", 
		target_monster_id = "Metadata/Monsters/DemonModular/DemonFemaleRangedMapBoss1", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulRalakeshUpgrade1", 
	},
	{
		id = "Garukhan", 
		ordinal = 1, 
		name = "Soul of Garukhan", 
		stat_text = "60% reduced Effect of [[Shock]] on you", 
	},
	{
		id = "Garukhan", 
		ordinal = 2, 
		name = "The Blacksmith", 
		stat_text = "Cannot be Blinded<br>You cannot be Maimed", 
		target_area_id = "MapWorldsDunes", 
		target_monster_id = "Metadata/Monsters/ZombieBoss/MapZombieBossHillock", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulGarukhanUpgrade1", 
	},
	{
		id = "Ryslatha", 
		ordinal = 1, 
		name = "Soul of Ryslatha", 
		stat_text = "[[Life]] Flasks gain 3 [[Charge|Charges]] every 3 seconds if you haven't used a [[Life]] Flask Recently<br>60% increased [[Life]] Recovery from Flasks used when on [[Low Life]]", 
	},
	{
		id = "Ryslatha", 
		ordinal = 2, 
		name = "Gorulis, Will-Thief", 
		stat_text = "Enemies you've [[Hit]] [[Recently]] have 50% reduced [[Life]] Regeneration rate", 
		target_area_id = "MapWorldsInfestedValley", 
		target_monster_id = "Metadata/Monsters/InsectSpawner/InsectSpawnerParasiteBossMap", 
		item_id = "Metadata/Items/PantheonSouls/PantheonSoulRyslathaUpgrade1", 
	}}
return data