local data = {	{
		pantheon_id = "TheBrineKing", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "cannot_be_stunned_if_have_been_stunned_or_blocked_stunning_hit_in_past_2_seconds", 
		value = 1, 
	},
	{
		pantheon_id = "TheBrineKing", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "base_stun_recovery_+%", 
		value = 30, 
	},
	{
		pantheon_id = "TheBrineKing", 
		pantheon_ordinal = 3, 
		ordinal = 1, 
		stat = "base_avoid_freeze_%", 
		value = 100, 
	},
	{
		pantheon_id = "TheBrineKing", 
		pantheon_ordinal = 4, 
		ordinal = 1, 
		stat = "chill_effectiveness_on_self_+%", 
		value = -50, 
	},
	{
		pantheon_id = "Arakaali", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "degen_effect_+%", 
		value = -10, 
	},
	{
		pantheon_id = "Arakaali", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "life_and_energy_shield_recovery_rate_+%_if_stopped_taking_damage_over_time_recently", 
		value = 20, 
	},
	{
		pantheon_id = "Arakaali", 
		pantheon_ordinal = 3, 
		ordinal = 1, 
		stat = "debuff_time_passed_+%", 
		value = 20, 
	},
	{
		pantheon_id = "Arakaali", 
		pantheon_ordinal = 4, 
		ordinal = 1, 
		stat = "additional_chaos_resistance_against_damage_over_time_%", 
		value = 40, 
	},
	{
		pantheon_id = "Solaris", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "physical_damage_reduction_%_if_only_one_enemy_nearby", 
		value = 6, 
	},
	{
		pantheon_id = "Solaris", 
		pantheon_ordinal = 1, 
		ordinal = 2, 
		stat = "take_half_area_damage_from_hit_%_chance", 
		value = 20, 
	},
	{
		pantheon_id = "Solaris", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "elemental_damage_taken_+%_if_not_hit_recently", 
		value = -8, 
	},
	{
		pantheon_id = "Solaris", 
		pantheon_ordinal = 3, 
		ordinal = 1, 
		stat = "self_take_no_extra_damage_from_critical_strikes_if_have_been_crit_recently", 
		value = 1, 
	},
	{
		pantheon_id = "Solaris", 
		pantheon_ordinal = 4, 
		ordinal = 1, 
		stat = "avoid_ailments_%_from_crit", 
		value = 50, 
	},
	{
		pantheon_id = "Lunaris", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "physical_damage_reduction_%_per_nearby_enemy", 
		value = 1, 
	},
	{
		pantheon_id = "Lunaris", 
		pantheon_ordinal = 1, 
		ordinal = 2, 
		stat = "movement_speed_+%_per_nearby_enemy", 
		value = 1, 
	},
	{
		pantheon_id = "Lunaris", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "base_avoid_projectiles_%_chance", 
		value = 10, 
	},
	{
		pantheon_id = "Lunaris", 
		pantheon_ordinal = 3, 
		ordinal = 1, 
		stat = "elemental_damage_taken_+%_if_been_hit_recently", 
		value = -6, 
	},
	{
		pantheon_id = "Lunaris", 
		pantheon_ordinal = 4, 
		ordinal = 1, 
		stat = "avoid_chained_projectile_%_chance", 
		value = 100, 
	},
	{
		pantheon_id = "Abberath", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "pantheon_abberath_ignite_duration_on_self_+%_final", 
		value = -60, 
	},
	{
		pantheon_id = "Abberath", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "unaffected_by_burning_ground", 
		value = 1, 
	},
	{
		pantheon_id = "Abberath", 
		pantheon_ordinal = 2, 
		ordinal = 2, 
		stat = "movement_speed_+%_while_on_burning_ground", 
		value = 10, 
	},
	{
		pantheon_id = "Gruthkul", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "physical_damage_reduction_%_per_hit_you_have_taken_recently", 
		value = 1, 
	},
	{
		pantheon_id = "Gruthkul", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "enemies_that_hit_you_with_attack_recently_attack_speed_+%", 
		value = -8, 
	},
	{
		pantheon_id = "Yugul", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "reflect_damage_taken_and_minion_reflect_damage_taken_+%", 
		value = -50, 
	},
	{
		pantheon_id = "Yugul", 
		pantheon_ordinal = 1, 
		ordinal = 2, 
		stat = "reflect_hexes_chance_%", 
		value = 50, 
	},
	{
		pantheon_id = "Yugul", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "curse_effect_on_self_+%", 
		value = -30, 
	},
	{
		pantheon_id = "Shakari", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "pantheon_shakari_self_poison_duration_+%_final", 
		value = -50, 
	},
	{
		pantheon_id = "Shakari", 
		pantheon_ordinal = 1, 
		ordinal = 2, 
		stat = "cannot_be_poisoned_if_x_poisons_on_you", 
		value = 3, 
	},
	{
		pantheon_id = "Shakari", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "chaos_damage_taken_+%", 
		value = -5, 
	},
	{
		pantheon_id = "Shakari", 
		pantheon_ordinal = 2, 
		ordinal = 2, 
		stat = "chaos_damage_taken_over_time_+%_while_in_caustic_cloud", 
		value = -25, 
	},
	{
		pantheon_id = "Tukohama", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "while_stationary_gain_additional_physical_damage_reduction_%", 
		value = 3, 
	},
	{
		pantheon_id = "Tukohama", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "life_regeneration_rate_per_minute_%_while_stationary", 
		value = 120, 
	},
	{
		pantheon_id = "Ralakesh", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "physical_damage_over_time_taken_+%_while_moving", 
		value = -25, 
	},
	{
		pantheon_id = "Ralakesh", 
		pantheon_ordinal = 1, 
		ordinal = 2, 
		stat = "no_extra_bleed_damage_while_moving", 
		value = 1, 
	},
	{
		pantheon_id = "Ralakesh", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "cannot_gain_corrupted_blood_while_you_have_at_least_5_stacks", 
		value = 1, 
	},
	{
		pantheon_id = "Garukhan", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "shocked_effect_on_self_+%", 
		value = -60, 
	},
	{
		pantheon_id = "Garukhan", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "cannot_be_blinded", 
		value = 1, 
	},
	{
		pantheon_id = "Garukhan", 
		pantheon_ordinal = 2, 
		ordinal = 2, 
		stat = "avoid_maim_%_chance", 
		value = 100, 
	},
	{
		pantheon_id = "Ryslatha", 
		pantheon_ordinal = 1, 
		ordinal = 1, 
		stat = "life_flasks_gain_X_charges_every_3_seconds_if_you_have_not_used_a_life_flask_recently", 
		value = 3, 
	},
	{
		pantheon_id = "Ryslatha", 
		pantheon_ordinal = 1, 
		ordinal = 2, 
		stat = "life_recovery_+%_from_flasks_while_on_low_life", 
		value = 60, 
	},
	{
		pantheon_id = "Ryslatha", 
		pantheon_ordinal = 2, 
		ordinal = 1, 
		stat = "enemy_life_regeneration_rate_+%_for_4_seconds_on_hit", 
		value = -50, 
	}}
return data