local data = {	{
		mod_id = "MapSynthesisedRareMonsterAdditionalCurrencyDrops1", 
		min_level = 13, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterAdditionalCurrencyDrops1", 
		min_level = 0, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMonsterAdditionalCurrencyDrops1", 
		min_level = 0, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalQualityCurrencyDrops1", 
		min_level = 13, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterAdditionalQualityCurrencyDrops1_", 
		min_level = 0, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMonsterAdditionalQualityCurrencyDrops1_", 
		min_level = 0, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterIncreasedFracturedItemDrops1", 
		min_level = 13, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterIncreasedFracturedItemDrops1__", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedMonsterIncreasedFracturedItemDrops1", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterCorruptDrops1_", 
		min_level = 20, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterCorruptDrops1", 
		min_level = 20, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMonsterCorruptDrops1", 
		min_level = 20, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterIncreasedMapDrops1", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterIncreasedMapDrops1__", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMonsterIncreasedMapDrops1_", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalDivinationCardDrops1", 
		min_level = 40, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterAdditionalDivinationCardDrops1", 
		min_level = 40, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMonsterAdditionalDivinationCardDrops1", 
		min_level = 40, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterIncreasedUniqueItemDrops1", 
		min_level = 13, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterIncreasedUniqueItemDrops1", 
		min_level = 0, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMonsterIncreasedUniqueItemDrops1", 
		min_level = 0, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterDroppedItemQuantity1", 
		min_level = 13, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterDroppedItemQuantity1_", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedMonsterDroppedItemQuantity1__", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterDroppedItemRarity1_", 
		min_level = 13, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterDroppedItemRarity1", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedMonsterDroppedItemRarity1", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterIncreasedExperience1", 
		min_level = 13, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterIncreasedExperience1", 
		min_level = 68, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedMonsterIncreasedExperience1", 
		min_level = 68, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalCurrencyShardDrops1", 
		min_level = 13, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterAdditionalCurrencyShardDrops1", 
		min_level = 0, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedMonsterAdditionalCurrencyShardDrops1", 
		min_level = 0, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalShaperItemDrops1_", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterAdditionalShaperItemDrops1", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMonsterAdditionalShaperItemDrops1______", 
		min_level = 68, 
		max_level = 100, 
		weight = 0, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalElderItemDrops1", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterAdditionalElderItemDrops1_", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMonsterAdditionalElderItemDrops1_", 
		min_level = 68, 
		max_level = 100, 
		weight = 0, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalBreachSplinterDrops1", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterAdditionalBreachSplinterDrops1", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMonsterAdditionalBreachSplinterDrops1_", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalFossilDrops1", 
		min_level = 40, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMagicMonsterAdditionalFossilDrops1", 
		min_level = 40, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedMonsterAdditionalFossilDrops1", 
		min_level = 40, 
		max_level = 100, 
		weight = 0, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalJewelDrops1", 
		min_level = 20, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalAbyssJewelDrops1_", 
		min_level = 50, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalMapDrop1", 
		min_level = 68, 
		max_level = 100, 
		weight = 37, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalTalismanDrops1", 
		min_level = 30, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalEssenceDrops1", 
		min_level = 13, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterResurrectAsAlly1", 
		min_level = 13, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterGiveModsToKiller1", 
		min_level = 13, 
		max_level = 100, 
		weight = 37, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalVaalFragmentDrops1", 
		min_level = 68, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterAdditionalVeiledItemDrops1", 
		min_level = 63, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterDuplicated1", 
		min_level = 13, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterDuplicated2__", 
		min_level = 13, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedRareMonsterDuplicated3", 
		min_level = 13, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedUpgradePackToMagic1", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedUpgradePackToRare1", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedAdditionalRareInPack1", 
		min_level = 13, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedSynthesisPackSize1__", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedSynthesisPackSize2_", 
		min_level = 40, 
		max_level = 100, 
		weight = 50, 
	},
	{
		mod_id = "MapSynthesisedAdditionalNormalAmbushChest", 
		min_level = 0, 
		max_level = 100, 
		weight = 120, 
	},
	{
		mod_id = "MapSynthesisedAdditionalMagicAmbushChest", 
		min_level = 20, 
		max_level = 100, 
		weight = 80, 
	},
	{
		mod_id = "MapSynthesisedAdditionalRareAmbushChest", 
		min_level = 40, 
		max_level = 100, 
		weight = 50, 
	}}
return data