name: export
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: ["develop"]

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.current-version.outputs.version }}
      updated: ${{ steps.updated-version.outputs.version }}
    steps:
      - id: current-version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
      - run: curl https://raw.githubusercontent.com/poe-tool-dev/latest-patch-version/main/latest.txt > version.txt
      - id: updated-version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"

  export:
    needs: check_version
    if: ${{ needs.check_version.outputs.current != needs.check_version.outputs.updated }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lvlvllvlvllvlvl/PyPoE
      - uses: actions/checkout@v4
        with:
          path: out
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - name: export data
        run: |
          poetry run pypoe_schema_import -a stable
          poetry run pypoe_exporter config set out_dir ./out/
          poetry run pypoe_exporter config set temp_dir ./out/
          poetry run pypoe_exporter config set version GENERATED
          poetry run pypoe_exporter setup perform
          poetry run ./export.bash -w -i md5sum
          poetry run ./export.bash -w atlas-icons
          if ! git -C ./out/ diff --quiet ./img/
          then
            poetry run ./export.bash -w -i .png
          fi
          cd ./out/img/
          ls -1 . | while read i ; do if [[ "$i" == *.png ]] && [[ ! -f "${i%.png}.md5sum" ]]; then touch "${i%.png}.md5sum"; fi; done
          git diff --name-only | while read i ; do if [[ "$i" == *.md5sum ]]; then zip images.zip "$(basename "$i" | sed s/md5sum/png/)"; fi; done
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: images-${{needs.check_version.outputs.updated}}
          path: ./out/img/images.zip
          if-no-files-found: ignore
          compression-level: 0
      - name: commit changes
        id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          repository: out
          commit_message: "[skip ci] Automated export ${{needs.check_version.outputs.updated}}"
